import type { Recipe } from "./types";

// The original built-in dishes.
export const CLASSIC: Recipe[] = [
{id:'kaprao',cuisine:'thai',course:'main',o:'th',mins:15,en:'Holy basil stir-fry on rice',th:'ผัดกะเพราราดข้าว',
 req:[['pork_mince','chicken','beef','pork'],['holy_basil'],['garlic'],['fish_sauce'],['rice'],['oil','olive_oil']],
 opt:['chilli','egg','oyster_sauce','sugar','soy_sauce'],
 subs:{holy_basil:['thai_basil','sweet_basil'],fish_sauce:['soy_sauce'],garlic:['shallot','garlic_powder']},
 st_en:['Cook the rice, or reheat leftover rice.','Pound garlic and chillies, then fry in hot oil for 30 seconds.','Add the meat and stir-fry on high heat until cooked and a little crisp.','Season with fish sauce, oyster sauce and a pinch of sugar.','Turn off the heat, fold in the basil and serve over rice, with a fried egg if you have one.'],
 st_th:['หุงข้าว หรืออุ่นข้าวที่เหลือ','โขลกกระเทียมกับพริก ผัดในน้ำมันร้อนราว 30 วินาที','ใส่เนื้อสัตว์ ผัดไฟแรงจนสุกและเริ่มกรอบ','ปรุงด้วยน้ำปลา ซอสหอยนางรม และน้ำตาลเล็กน้อย','ปิดไฟ ใส่ใบกะเพรา คลุกเร็ว ๆ ตักราดข้าว เสิร์ฟพร้อมไข่ดาวถ้ามี']},
{id:'fried_rice',cuisine:'thai',course:'main',o:'th',mins:15,en:'Clear-the-fridge fried rice',th:'ข้าวผัดล้างตู้เย็น',
 req:[['rice'],['egg'],['oil','olive_oil'],['soy_sauce','fish_sauce']],
 opt:['pork_mince','chicken','pork','shrimp','bacon','ham','onion','garlic','spring_onion','carrot','tomato','cabbage','broccoli','cucumber','lime','sugar'],subs:{},
 st_en:['Use day-old rice if you have it; spread fresh rice out to cool.','Fry garlic and onion, then any meat or chopped veg until just cooked.','Push to one side, scramble the eggs, then add the rice and toss on high heat.','Season with soy or fish sauce and a pinch of sugar.','Serve with cucumber, spring onion and a squeeze of lime.'],
 st_th:['ใช้ข้าวค้างคืนถ้ามี ถ้าเป็นข้าวหุงใหม่ให้เกลี่ยพักให้เย็น','เจียวกระเทียมกับหอมใหญ่ ใส่เนื้อสัตว์หรือผักหั่นที่มี ผัดพอสุก','ดันไว้ข้างกระทะ ตอกไข่ยีให้สุก แล้วใส่ข้าว ผัดไฟแรง','ปรุงด้วยซีอิ๊วหรือน้ำปลา และน้ำตาลเล็กน้อย','เสิร์ฟกับแตงกวา ต้นหอม และบีบมะนาว']},
{id:'khai_jiao',cuisine:'thai',course:'main',o:'th',mins:10,en:'Thai crispy omelette on rice',th:'ไข่เจียวราดข้าว',
 req:[['egg'],['rice'],['fish_sauce','soy_sauce'],['oil','olive_oil']],
 opt:['pork_mince','onion','spring_onion','shallot','tomato','chilli'],subs:{},
 st_en:['Beat the eggs hard with a splash of fish sauce until frothy.','Stir in minced pork, spring onion or onion if you have them.','Heat plenty of oil until shimmering, then pour the eggs in from a height.','Flip once the edges puff and turn golden; drain and serve on rice.'],
 st_th:['ตีไข่ให้ขึ้นฟูกับน้ำปลาเล็กน้อย','ใส่หมูสับ ต้นหอม หรือหอมใหญ่ถ้ามี','ตั้งน้ำมันให้ร้อนจัด เทไข่ลงจากที่สูง','กลับด้านเมื่อขอบพองและเหลือง ซับน้ำมัน วางบนข้าวสวย']},
{id:'pak_boong',cuisine:'thai',course:'side',o:'th',mins:8,en:'Flash-fried greens with garlic',th:'ผัดผักบุ้งไฟแดง',
 req:[['morning_glory'],['garlic'],['oyster_sauce','soy_sauce'],['oil','olive_oil']],
 opt:['chilli','fish_sauce','sugar','rice'],
 subs:{morning_glory:['chinese_kale','spinach','broccoli','cabbage'],garlic:['garlic_powder']},
 st_en:['Cut the greens into 5 cm lengths, keeping stems and leaves apart.','Crush garlic and chillies and pile them on the greens with the sauces.','Heat the wok until smoking, add oil, then everything at once.','Toss for about a minute until just wilted and serve straight away.'],
 st_th:['หั่นผักยาว 5 ซม. แยกก้านกับใบ','ทุบกระเทียมกับพริก วางบนผักพร้อมเครื่องปรุง','ตั้งกระทะให้ร้อนจัด ใส่น้ำมัน แล้วเทผักลงทีเดียว','ผัดเร็ว ๆ ราว 1 นาทีพอผักสลด ตักเสิร์ฟทันที']},
{id:'tom_kha',cuisine:'thai',course:'soup',o:'th',mins:25,en:'Coconut galangal soup',th:'ต้มข่าไก่',
 req:[['chicken','shrimp','mushroom','tofu'],['coconut_milk'],['galangal'],['lemongrass'],['fish_sauce']],
 opt:['kaffir','mushroom','lime','chilli','coriander','shallot','sugar'],
 subs:{galangal:['ginger'],lemongrass:['lime'],fish_sauce:['soy_sauce','salt']},
 st_en:['Bruise the lemongrass and slice the galangal; simmer in coconut milk with a splash of water and torn lime leaves.','Add the chicken (or mushrooms or tofu) and simmer gently for 10 minutes.','Season with fish sauce and a little sugar; keep it below a hard boil so it stays smooth.','Off the heat, add lime juice and chillies, then top with coriander.'],
 st_th:['ทุบตะไคร้ หั่นข่า ต้มกับกะทิผสมน้ำเล็กน้อยและใบมะกรูดฉีก','ใส่ไก่ (หรือเห็ด เต้าหู้) เคี่ยวไฟอ่อนราว 10 นาที','ปรุงด้วยน้ำปลาและน้ำตาลเล็กน้อย อย่าให้เดือดจัดกะทิจะแตกมัน','ปิดไฟ บีบมะนาว ใส่พริก โรยผักชี']},
{id:'green_curry',cuisine:'thai',course:'main',o:'th',mins:30,en:'Green curry',th:'แกงเขียวหวาน',
 req:[['chicken','pork','beef','fish','shrimp','tofu'],['green_curry_paste'],['coconut_milk'],['fish_sauce']],
 opt:['thai_basil','chilli','kaffir','bell_pepper','broccoli','mushroom','sugar','rice'],
 subs:{green_curry_paste:['red_curry_paste'],fish_sauce:['soy_sauce']},
 st_en:['Fry the curry paste in a few spoons of coconut cream until fragrant and oily.','Add the meat and stir until coated and nearly cooked.','Pour in the rest of the coconut milk with some water, add veg and simmer 10 minutes.','Season with fish sauce and sugar, finish with basil and chilli, serve with rice.'],
 st_th:['ผัดพริกแกงกับหัวกะทิจนหอมและแตกมัน','ใส่เนื้อสัตว์ ผัดให้เข้ากันจนเกือบสุก','เติมกะทิที่เหลือกับน้ำ ใส่ผัก เคี่ยว 10 นาที','ปรุงด้วยน้ำปลา น้ำตาล ใส่โหระพาและพริก เสิร์ฟกับข้าวสวย']},
{id:'pad_see_ew',cuisine:'thai',course:'main',o:'th',mins:15,en:'Soy-glazed stir-fried noodles',th:'ผัดซีอิ๊ว',
 req:[['noodles'],['chinese_kale'],['egg'],['soy_sauce'],['oil','olive_oil']],
 opt:['pork','chicken','pork_mince','garlic','oyster_sauce','sugar'],
 subs:{chinese_kale:['broccoli','cabbage','spinach'],noodles:['pasta']},
 st_en:['Separate the noodles; slice the greens, keeping stems thin.','Fry garlic and meat in hot oil, then add the stems.','Add noodles and soy sauce, let them sit a moment to char, then toss.','Push aside, scramble an egg, add the leaves and toss everything together.'],
 st_th:['แยกเส้นไม่ให้ติดกัน หั่นคะน้าแยกก้านบาง ๆ','เจียวกระเทียม ใส่เนื้อสัตว์ แล้วตามด้วยก้านผัก','ใส่เส้นกับซีอิ๊ว ปล่อยให้ติดกระทะให้หอมไหม้นิด ๆ แล้วผัด','ดันเส้นไว้ข้าง ตอกไข่ยี ใส่ใบผัก ผัดรวมกัน']},
{id:'frittata',cuisine:'italian',course:'main',o:'uk',mins:20,en:'Use-it-up frittata',th:'ฟริตตาตาเก็บตกผัก',
 req:[['egg'],['potato','spinach','mushroom','broccoli','bell_pepper','tomato'],['olive_oil','oil','butter'],['salt','fish_sauce']],
 opt:['cheese','onion','bacon','ham','milk','pepper','spring_onion','sweet_basil'],subs:{},
 st_en:['Heat the grill. Soften onion and any veg in an ovenproof pan with oil.','Beat the eggs with salt, pepper and a splash of milk; stir in grated cheese.','Pour over the veg and cook gently until the edges set.','Finish under the grill for 3 to 4 minutes until puffed and golden.'],
 st_th:['เปิดเตาย่างรอ ผัดหอมใหญ่และผักที่มีในกระทะที่เข้าเตาได้','ตีไข่กับเกลือ พริกไทย และนมเล็กน้อย ใส่ชีสขูด','เทไข่ลงบนผัก ใช้ไฟอ่อนจนขอบเริ่มเซ็ตตัว','นำเข้าเตาย่าง 3–4 นาทีจนฟูและเหลือง']},
{id:'pasta_tomato',cuisine:'italian',course:'main',o:'uk',mins:20,en:'Garlic tomato pasta',th:'พาสต้าซอสมะเขือเทศกระเทียม',
 req:[['pasta'],['tinned_tomato','tomato'],['garlic','garlic_powder'],['olive_oil','oil'],['salt']],
 opt:['onion','cheese','sweet_basil','bacon','tuna','mushroom','chilli','pepper','spinach','sugar'],
 subs:{pasta:['noodles'],salt:['soy_sauce','fish_sauce']},
 st_en:['Boil the pasta in well-salted water.','Gently fry garlic and onion in olive oil, add the tomatoes and a pinch of sugar, simmer 10 minutes.','Stir in any extras (tuna, bacon, spinach) and loosen with pasta water.','Toss with the pasta; finish with cheese and basil.'],
 st_th:['ต้มพาสต้าในน้ำเค็ม','ผัดกระเทียมและหอมใหญ่ในน้ำมันมะกอกไฟอ่อน ใส่มะเขือเทศกับน้ำตาลเล็กน้อย เคี่ยว 10 นาที','ใส่ของที่มี เช่น ทูน่า เบคอน ผักโขม เติมน้ำต้มเส้นให้ซอสลื่น','คลุกกับเส้น โรยชีสและใบเบซิล']},
{id:'creamy_pasta',cuisine:'italian',course:'main',o:'uk',mins:20,en:'Creamy mushroom pasta',th:'พาสต้าครีมเห็ด',
 req:[['pasta'],['mushroom'],['cream','milk','cheese'],['garlic','garlic_powder'],['butter','olive_oil','oil']],
 opt:['spinach','onion','bacon','cheese','pepper','salt'],
 subs:{mushroom:['spinach','broccoli'],pasta:['noodles']},
 st_en:['Boil the pasta.','Fry the mushrooms in butter on high heat until browned, then add garlic.','Add cream or milk and simmer until slightly thickened; season well.','Toss in the pasta and any spinach, finish with cheese and black pepper.'],
 st_th:['ต้มพาสต้า','ผัดเห็ดกับเนยไฟแรงจนเหลือง แล้วใส่กระเทียม','เติมครีมหรือนม เคี่ยวจนข้นเล็กน้อย ปรุงรส','ใส่เส้นและผักโขม คลุก โรยชีสและพริกไทย']},
{id:'cheese_toast',cuisine:'british',course:'snack',o:'uk',mins:8,en:'Loaded cheese on toast',th:'ขนมปังปิ้งหน้าชีส',
 req:[['bread'],['cheese']],
 opt:['tomato','ham','egg','onion','butter','pepper','spring_onion','milk'],subs:{},
 st_en:['Toast the bread lightly on both sides.','Top with sliced tomato or ham if you have them.','Cover with grated cheese loosened with a little milk or egg.','Grill until bubbling and spotted brown.'],
 st_th:['ปิ้งขนมปังเบา ๆ ทั้งสองด้าน','วางมะเขือเทศหรือแฮมถ้ามี','โรยชีสขูดผสมนมหรือไข่เล็กน้อย','อบหรือย่างจนชีสเดือดและเป็นจุดสีน้ำตาล']},
{id:'bubble',cuisine:'british',course:'side',o:'uk',mins:25,en:'Bubble and squeak',th:'บับเบิลแอนด์สควีก (มันฝรั่งทอดกับผัก)',
 req:[['potato'],['cabbage','chinese_kale','spinach','broccoli','carrot'],['butter','oil','olive_oil'],['salt','soy_sauce']],
 opt:['onion','egg','bacon','pepper','cheese'],subs:{},
 st_en:['Boil the potatoes (or use leftovers) and crush them roughly.','Shred the greens and cook them briefly.','Mix potato, greens and fried onion, and season well.','Press into a hot buttered pan, fry until a crust forms, flip in pieces and serve with a fried egg.'],
 st_th:['ต้มมันฝรั่ง (หรือใช้ที่เหลือ) บดหยาบ ๆ','ซอยผักแล้วลวกหรือผัดสั้น ๆ','ผสมมันฝรั่ง ผัก และหอมใหญ่ผัด ปรุงรส','กดลงกระทะร้อนที่ทาเนย ทอดจนเกิดเปลือกกรอบ พลิกเป็นชิ้น ๆ เสิร์ฟกับไข่ดาว']},
{id:'traybake',cuisine:'british',course:'main',o:'uk',mins:45,en:'Chicken and veg traybake',th:'ไก่อบผักถาดเดียว',
 req:[['chicken'],['potato','carrot','broccoli','bell_pepper'],['olive_oil','oil'],['salt']],
 opt:['onion','garlic','garlic_powder','pepper','lime','tomato'],
 subs:{chicken:['pork','fish'],salt:['soy_sauce']},
 st_en:['Heat the oven to 200°C (180°C fan).','Chop the veg into even chunks and toss with oil, salt, pepper and garlic.','Sit the chicken on top and roast for 35 to 40 minutes.','Rest 5 minutes and squeeze over lime or lemon.'],
 st_th:['เปิดเตาอบ 200°C (พัดลม 180°C)','หั่นผักขนาดเท่า ๆ กัน คลุกน้ำมัน เกลือ พริกไทย กระเทียม','วางไก่ด้านบน อบ 35–40 นาที','พักไว้ 5 นาที บีบมะนาวก่อนเสิร์ฟ']},
{id:'veg_soup',cuisine:'british',course:'soup',o:'uk',mins:30,en:'Odds-and-ends veg soup',th:'ซุปผักเก็บตก',
 req:[['onion','shallot'],['carrot','potato','tomato','cabbage','broccoli','spinach'],['stock'],['oil','olive_oil','butter']],
 opt:['tinned_tomato','garlic','pepper','salt','cream','bread'],
 subs:{stock:['soy_sauce','fish_sauce']},
 st_en:['Soften the onion in oil for 5 minutes.','Add all the chopped veg and stir for 2 minutes.','Cover with stock and simmer 20 minutes until soft.','Blend or mash, season, and serve with toast.'],
 st_th:['ผัดหอมใหญ่ในน้ำมัน 5 นาทีจนนิ่ม','ใส่ผักหั่นทั้งหมด ผัด 2 นาที','เติมน้ำซุปให้ท่วม เคี่ยว 20 นาทีจนผักนุ่ม','ปั่นหรือบด ปรุงรส เสิร์ฟกับขนมปังปิ้ง']},
{id:'khao_tom',cuisine:'thai',course:'breakfast',o:'th',mins:20,en:'Thai rice soup',th:'ข้าวต้ม',
 req:[['rice'],['pork_mince','chicken','shrimp','fish','egg'],['fish_sauce','soy_sauce']],
 opt:['ginger','spring_onion','coriander','garlic','pepper','egg','stock'],subs:{},
 st_en:['Bring stock or water to the boil with sliced ginger.','Add cooked rice and simmer until it starts to break down.','Drop in small balls of seasoned pork (or chicken or prawns) and cook through.','Season with fish sauce and white pepper; top with fried garlic, spring onion and coriander.'],
 st_th:['ต้มน้ำซุปหรือน้ำเปล่ากับขิงซอย','ใส่ข้าวสวย เคี่ยวจนเม็ดข้าวเริ่มบาน','ปั้นหมูสับที่หมักแล้วเป็นก้อนเล็ก ๆ ใส่ลงไปจนสุก','ปรุงด้วยน้ำปลาและพริกไทย โรยกระเทียมเจียว ต้นหอม ผักชี']},
{id:'cabbage_fs',cuisine:'thai',course:'side',o:'th',mins:10,en:'Charred cabbage with fish sauce',th:'กะหล่ำปลีผัดน้ำปลา',
 req:[['cabbage'],['garlic'],['fish_sauce'],['oil','olive_oil']],
 opt:['pork','pork_mince','sugar','chilli'],
 subs:{fish_sauce:['soy_sauce'],cabbage:['chinese_kale','broccoli'],garlic:['garlic_powder']},
 st_en:['Tear the cabbage into bite-sized pieces.','Fry garlic in oil until golden, then add the cabbage on the highest heat.','Let it char in places, then season with fish sauce and a pinch of sugar.','Serve as soon as the leaves turn glossy but still crunchy.'],
 st_th:['ฉีกกะหล่ำปลีเป็นชิ้นพอคำ','เจียวกระเทียมจนเหลือง ใส่กะหล่ำ ใช้ไฟแรงสุด','ปล่อยให้ไหม้เป็นจุด ๆ ปรุงด้วยน้ำปลาและน้ำตาลเล็กน้อย','ตักเสิร์ฟเมื่อใบเงาแต่ยังกรอบ']},
{id:'tuna_rice',cuisine:'thai',course:'main',o:'both',mins:10,en:'Spicy tuna rice bowl',th:'ข้าวยำทูน่า',
 req:[['rice'],['tuna'],['soy_sauce','fish_sauce']],
 opt:['egg','cucumber','spring_onion','chilli','lime','onion','sugar','coriander'],subs:{},
 st_en:['Warm the rice.','Mix the tuna with soy or fish sauce, lime, chilli and sliced onion.','Spoon over the rice with sliced cucumber.','Top with a fried or jammy egg and spring onion.'],
 st_th:['อุ่นข้าวสวย','ยำทูน่ากับซีอิ๊วหรือน้ำปลา มะนาว พริก และหอมซอย','ตักราดบนข้าว วางแตงกวาหั่น','ใส่ไข่ดาวหรือไข่ยางมะตูม โรยต้นหอม']}
];
