import { r } from "./types";

// Thai sweets, British puddings and international desserts. Most serve 2–4.
export const DESSERTS = [
  // ---- Thai ----
  r("mango_sticky_rice", "th", "thai", "dessert", 45, "Mango sticky rice", "ข้าวเหนียวมะม่วง",
    "sticky_rice; coconut_milk; mango; sugar|palm_sugar", "salt pandan", "sugar>honey,condensed_milk",
    ["Soak sticky rice for at least 2 hours (or overnight), then steam for 20–25 minutes.", "Warm coconut milk with sugar and a good pinch of salt; pour most over the hot rice and cover for 15 minutes.", "Simmer the rest of the coconut milk with a little cornflour for the topping.", "Serve with sliced ripe mango and the salty-sweet topping."],
    ["แช่ข้าวเหนียวอย่างน้อย 2 ชั่วโมง (หรือข้ามคืน) นึ่ง 20–25 นาที", "อุ่นกะทิกับน้ำตาลและเกลือหยิบมือ ราดบนข้าวเหนียวร้อน ๆ ปิดฝาพัก 15 นาที", "เคี่ยวกะทิที่เหลือกับแป้งเล็กน้อยทำหัวกะทิราดหน้า", "เสิร์ฟกับมะม่วงสุกหั่นชิ้นและหัวกะทิรสหวานเค็ม"]),
  r("bua_loy", "th", "thai", "dessert", 40, "Rice balls in coconut milk", "บัวลอย",
    "glutinous_rice_flour; coconut_milk; sugar|palm_sugar", "pandan taro pumpkin egg salt", "",
    ["Mix glutinous rice flour with mashed pumpkin or taro (or water) into a soft dough.", "Roll into small balls and boil until they float; drain.", "Warm coconut milk with sugar, a pinch of salt and a pandan leaf.", "Add the balls and serve warm; a soft-poached egg on top is the classic extra."],
    ["นวดแป้งข้าวเหนียวกับฟักทองหรือเผือกบด (หรือน้ำ) จนเป็นก้อนนิ่ม", "ปั้นเป็นเม็ดเล็ก ต้มจนลอย ตักขึ้น", "อุ่นกะทิกับน้ำตาล เกลือหยิบมือ และใบเตย", "ใส่แป้งลงไป เสิร์ฟอุ่น ๆ จะใส่ไข่หวานด้วยก็ได้"]),
  r("gluay_buat_chee", "th", "thai", "dessert", 20, "Bananas in coconut milk", "กล้วยบวชชี",
    "banana; coconut_milk; sugar|palm_sugar", "salt pandan", "",
    ["Cut ripe bananas into chunks.", "Bring coconut milk and a little water to a gentle simmer with a pandan leaf.", "Add bananas, sugar and a pinch of salt; simmer 5 minutes.", "Serve warm."],
    ["หั่นกล้วยสุกเป็นท่อน", "ต้มกะทิกับน้ำเล็กน้อยและใบเตยไฟอ่อน", "ใส่กล้วย น้ำตาล และเกลือหยิบมือ เคี่ยว 5 นาที", "เสิร์ฟอุ่น ๆ"]),
  r("fak_thong_gaeng_buat", "th", "thai", "dessert", 25, "Pumpkin in coconut milk", "ฟักทองแกงบวด",
    "pumpkin; coconut_milk; palm_sugar|sugar", "salt pandan", "pumpkin>sweet_potato,taro",
    ["Peel pumpkin and cut into bite-sized pieces.", "Simmer in coconut milk and a little water until just tender.", "Stir in palm sugar and a pinch of salt; cook 2 more minutes.", "Serve warm or at room temperature."],
    ["ปอกฟักทอง หั่นชิ้นพอคำ", "ต้มในกะทิกับน้ำเล็กน้อยจนเริ่มนุ่ม", "ใส่น้ำตาลปี๊บและเกลือหยิบมือ ต้มต่ออีก 2 นาที", "เสิร์ฟอุ่นหรือพักให้เย็น"]),
  r("woon_kati", "th", "thai", "dessert", 30, "Coconut jelly", "วุ้นกะทิ",
    "agar; coconut_milk; sugar", "pandan salt", "",
    ["Boil agar powder in water with a pandan leaf until fully dissolved; add sugar.", "Pour half into a tray and let it set for 5 minutes.", "Add coconut milk and a pinch of salt to the rest, heat, then pour on top.", "Chill for an hour and cut into squares."],
    ["ต้มผงวุ้นกับน้ำและใบเตยจนละลายหมด ใส่น้ำตาล", "เทครึ่งหนึ่งลงถาด พักให้เซ็ตตัว 5 นาที", "ใส่กะทิกับเกลือหยิบมือในส่วนที่เหลือ อุ่นแล้วเทเป็นชั้นบน", "แช่เย็น 1 ชั่วโมง ตัดเป็นชิ้น"]),
  r("sakoo_khao_pod", "th", "thai", "dessert", 25, "Tapioca pearls with sweetcorn", "สาคูเปียกข้าวโพด",
    "tapioca_pearls; coconut_milk; sugar", "sweetcorn salt pandan", "",
    ["Boil tapioca pearls in plenty of water until almost clear, stirring so they do not stick.", "Add sugar and sweetcorn; simmer until fully clear.", "Warm coconut milk with a pinch of salt.", "Serve the tapioca with salty coconut cream on top."],
    ["ต้มสาคูในน้ำเยอะ ๆ จนเกือบใส คนเรื่อย ๆ ไม่ให้ติดกัน", "ใส่น้ำตาลและข้าวโพด ต้มจนใสหมด", "อุ่นกะทิกับเกลือหยิบมือ", "ตักสาคูราดหัวกะทิรสเค็มนิด ๆ"]),
  r("tao_suan", "th", "thai", "dessert", 40, "Mung bean pudding", "เต้าส่วน",
    "mung_beans; sugar; cornflour|tapioca_pearls; coconut_milk", "salt pandan", "",
    ["Soak split mung beans for an hour, then steam or boil until soft.", "Boil water with sugar and a pandan leaf; thicken with cornflour mixed in water until glossy.", "Stir in the beans.", "Serve with salty coconut cream on top."],
    ["แช่ถั่วเขียวเราะเปลือก 1 ชั่วโมง นึ่งหรือต้มจนนุ่ม", "ต้มน้ำกับน้ำตาลและใบเตย ข้นด้วยแป้งละลายน้ำจนใสเงา", "ใส่ถั่วเขียวคนให้เข้ากัน", "ราดหัวกะทิรสเค็มนิด ๆ"]),
  r("khanom_tuay", "th", "thai", "dessert", 35, "Coconut custard cups", "ขนมถ้วย",
    "glutinous_rice_flour|flour|cornflour; coconut_milk; sugar", "pandan salt", "",
    ["For the base, mix flour, sugar, pandan juice and water; for the top, mix coconut milk, a little flour and salt.", "Steam small cups for 5 minutes to heat them.", "Fill two-thirds with the base and steam 7 minutes until set.", "Add the coconut layer and steam 5 more minutes."],
    ["ตัวขนม ผสมแป้ง น้ำตาล น้ำใบเตย และน้ำ หน้ากะทิ ผสมกะทิ แป้งเล็กน้อย และเกลือ", "นึ่งถ้วยเปล่า 5 นาทีให้ร้อน", "หยอดตัวขนมสองในสาม นึ่ง 7 นาทีจนเซ็ต", "หยอดหน้ากะทิ นึ่งต่ออีก 5 นาที"]),
  r("sangkaya", "th", "thai", "dessert", 25, "Coconut custard with toast", "สังขยาใบเตย",
    "egg; coconut_milk|milk; sugar|palm_sugar", "pandan bread cornflour", "",
    ["Whisk eggs with sugar until dissolved.", "Add coconut milk and pandan juice; strain.", "Cook over a very low heat (or steam), stirring, until thick like custard.", "Serve with toasted bread for dipping."],
    ["ตีไข่กับน้ำตาลจนละลาย", "ใส่กะทิและน้ำใบเตย กรอง", "กวนไฟอ่อนมาก (หรือนึ่ง) คนตลอดจนข้นเป็นครีม", "เสิร์ฟกับขนมปังปิ้งสำหรับจิ้ม"]),
  r("gluay_tod", "th", "thai", "dessert", 25, "Thai fried bananas", "กล้วยทอด",
    "banana; flour|glutinous_rice_flour|cornflour; oil", "coconut_milk sugar salt", "",
    ["Slice bananas lengthways.", "Make a batter of flour, coconut milk (or water), sugar and a pinch of salt.", "Dip and fry in hot oil until golden and crisp.", "Drain on paper and eat warm."],
    ["ฝานกล้วยตามยาว", "ผสมแป้ง กะทิ (หรือน้ำ) น้ำตาล และเกลือหยิบมือ เป็นแป้งชุบ", "ชุบแล้วทอดในน้ำมันร้อนจนเหลืองกรอบ", "ซับน้ำมัน กินอุ่น ๆ"]),
  r("roti_gluay", "th", "thai", "dessert", 20, "Banana roti", "โรตีกล้วย",
    "flour|tortillas; banana; egg; butter|oil", "condensed_milk sugar", "",
    ["Use ready tortillas, or knead flour, water and a little oil into a soft dough and rest it; stretch very thin.", "Put sliced banana in the middle, pour over beaten egg and fold into a square.", "Fry in butter until golden on both sides.", "Cut into squares; drizzle with condensed milk and sugar."],
    ["ใช้แผ่นตอร์ติญ่าสำเร็จ หรือนวดแป้งกับน้ำและน้ำมันเล็กน้อย พักไว้ แล้วคลึงให้บางมาก", "วางกล้วยฝานตรงกลาง ราดไข่ตี พับเป็นสี่เหลี่ยม", "ทอดกับเนยจนเหลืองทั้งสองด้าน", "ตัดเป็นชิ้น ราดนมข้นหวานและน้ำตาล"]),

  // ---- British ----
  r("apple_crumble", "uk", "british", "dessert", 50, "Apple crumble", "แอปเปิลครัมเบิล",
    "apple|berries; flour|oats; butter; sugar", "cinnamon cream honey", "sugar>honey",
    ["Heat the oven to 190°C. Slice apples into a dish with a spoon of sugar and cinnamon.", "Rub flour (or oats) and butter together to crumbs; stir in sugar.", "Scatter over the fruit.", "Bake 30–35 minutes until golden and bubbling; serve with cream or custard."],
    ["เปิดเตาอบ 190°C หั่นแอปเปิลใส่ถาด โรยน้ำตาลและอบเชย", "ขยี้แป้ง (หรือข้าวโอ๊ต) กับเนยจนเป็นเม็ดร่วน ใส่น้ำตาล", "โรยหน้าผลไม้", "อบ 30–35 นาทีจนเหลืองและเดือดปุด เสิร์ฟกับครีมหรือคัสตาร์ด"]),
  r("rice_pudding", "uk", "british", "dessert", 40, "Creamy rice pudding", "ข้าวพุดดิ้งนม",
    "rice; milk; sugar", "vanilla cinnamon cream butter berries", "sugar>honey,condensed_milk",
    ["Put 80 g rice and 700 ml milk in a pan with sugar.", "Simmer very gently, stirring often, for 30–35 minutes until creamy.", "Stir in vanilla and a splash of cream.", "Serve warm with cinnamon or jam."],
    ["ใส่ข้าว 80 กรัมกับนม 700 มล. และน้ำตาลลงหม้อ", "เคี่ยวไฟอ่อนมาก คนบ่อย ๆ 30–35 นาทีจนข้นครีมมี่", "ใส่วานิลลาและครีมเล็กน้อย", "เสิร์ฟอุ่นกับอบเชยหรือแยม"]),
  r("scones", "uk", "british", "dessert", 30, "Scones", "สโคน",
    "flour; butter; milk; baking_powder", "sugar berries cream egg", "",
    ["Heat the oven to 220°C. Rub 225 g flour, 2 tsp baking powder and 50 g butter to crumbs; add a spoon of sugar.", "Stir in about 120 ml milk to a soft dough; do not overwork.", "Pat 3 cm thick, cut rounds and brush the tops with milk or egg.", "Bake 10–12 minutes; serve with cream and jam or berries."],
    ["เปิดเตาอบ 220°C ขยี้แป้ง 225 กรัม ผงฟู 2 ช้อนชา และเนย 50 กรัมจนร่วน ใส่น้ำตาลหนึ่งช้อน", "ใส่นมราว 120 มล. ผสมเป็นก้อนนิ่ม อย่านวดนาน", "กดให้หนา 3 ซม. ตัดเป็นวงกลม ทาหน้าด้วยนมหรือไข่", "อบ 10–12 นาที เสิร์ฟกับครีมและแยมหรือเบอร์รี่"]),
  r("bread_butter_pudding", "uk", "british", "dessert", 50, "Bread and butter pudding", "พุดดิ้งขนมปังเนย",
    "bread; egg; milk; sugar; butter", "cinnamon vanilla cream", "sugar>honey",
    ["Butter slices of bread (stale is best), cut into triangles and layer in a dish.", "Whisk eggs, milk, sugar and vanilla; pour over and leave 15 minutes.", "Sprinkle with cinnamon and a little sugar.", "Bake at 180°C for 30–35 minutes until puffed and just set."],
    ["ทาเนยบนขนมปัง (ขนมปังเก่ายิ่งดี) ตัดเป็นสามเหลี่ยม เรียงในถาด", "ตีไข่ นม น้ำตาล และวานิลลา เทราด พักไว้ 15 นาที", "โรยอบเชยและน้ำตาลเล็กน้อย", "อบ 180°C ราว 30–35 นาทีจนฟูและเซ็ตตัว"]),
  r("flapjacks", "uk", "british", "snack", 35, "Flapjacks", "แฟลปแจ็ค (ขนมข้าวโอ๊ต)",
    "oats; butter; honey|sugar", "banana peanut_butter berries", "",
    ["Heat the oven to 180°C. Melt 125 g butter with 100 g honey or golden syrup and a little sugar.", "Stir in 250 g oats (and mashed banana or peanut butter if you like).", "Press into a lined tin.", "Bake 20–25 minutes until golden; cut into bars while warm."],
    ["เปิดเตาอบ 180°C ละลายเนย 125 กรัมกับน้ำผึ้ง 100 กรัมและน้ำตาลเล็กน้อย", "ใส่ข้าวโอ๊ต 250 กรัม (ใส่กล้วยบดหรือเนยถั่วก็ได้)", "กดลงพิมพ์ที่รองกระดาษ", "อบ 20–25 นาทีจนเหลือง ตัดเป็นแท่งตอนยังอุ่น"]),
  r("uk_pancakes", "uk", "british", "dessert", 20, "Thin pancakes with lemon and sugar", "แพนเค้กแผ่นบาง มะนาวน้ำตาล",
    "flour; egg; milk", "lime sugar butter banana chocolate", "",
    ["Whisk 100 g flour, 2 eggs and 300 ml milk into a smooth batter.", "Heat a little butter in a frying pan and swirl in a thin layer of batter.", "Cook 1 minute, flip, cook 30 seconds more.", "Squeeze over lemon and sprinkle with sugar; roll up."],
    ["ตีแป้ง 100 กรัม ไข่ 2 ฟอง และนม 300 มล. ให้เนียน", "ตั้งกระทะทาเนย เทแป้งบาง ๆ แล้วเอียงให้ทั่ว", "ทอด 1 นาที กลับด้าน ทอดอีก 30 วินาที", "บีบมะนาว โรยน้ำตาล ม้วนกิน"]),

  // ---- American ----
  r("fluffy_pancakes", "both", "american", "breakfast", 20, "Fluffy pancakes", "แพนเค้กฟู",
    "flour; egg; milk; baking_powder", "butter honey berries banana sugar", "",
    ["Mix 150 g flour, 2 tsp baking powder and a spoon of sugar; whisk in 1 egg and 200 ml milk.", "Leave the thick batter to rest 5 minutes.", "Cook ladlefuls on a buttered pan until bubbles pop on top; flip.", "Serve stacked with honey, berries or banana."],
    ["ผสมแป้ง 150 กรัม ผงฟู 2 ช้อนชา และน้ำตาลหนึ่งช้อน ตีกับไข่ 1 ฟองและนม 200 มล.", "พักแป้งข้น ๆ 5 นาที", "ตักแป้งลงกระทะทาเนย พอมีฟองขึ้นด้านบนให้กลับด้าน", "เรียงซ้อน ราดน้ำผึ้ง ใส่เบอร์รี่หรือกล้วย"]),
  r("brownies", "both", "american", "dessert", 40, "Chocolate brownies", "บราวนี่",
    "chocolate|cocoa; butter; sugar; egg; flour", "vanilla peanuts", "",
    ["Heat the oven to 180°C. Melt 100 g chocolate with 100 g butter.", "Whisk in 150 g sugar and 2 eggs until glossy.", "Fold in 60 g flour (and 2 spoons of cocoa if using).", "Bake in a lined tin 20–25 minutes; the middle should still be fudgy."],
    ["เปิดเตาอบ 180°C ละลายช็อกโกแลต 100 กรัมกับเนย 100 กรัม", "ตีกับน้ำตาล 150 กรัมและไข่ 2 ฟองจนเงา", "ตะล่อมแป้ง 60 กรัม (และโกโก้ 2 ช้อนถ้ามี)", "อบในพิมพ์ที่รองกระดาษ 20–25 นาที ตรงกลางยังหนึบ"]),
  r("choc_chip_cookies", "both", "american", "dessert", 30, "Chocolate chip cookies", "คุกกี้ช็อกโกแลตชิป",
    "flour; butter; sugar; chocolate", "egg vanilla baking_powder peanuts", "",
    ["Heat the oven to 180°C. Beat 100 g soft butter with 120 g sugar.", "Beat in an egg and vanilla, then 180 g flour and ½ tsp baking powder.", "Stir in chopped chocolate; roll into balls.", "Bake spaced apart 10–12 minutes; they firm up as they cool."],
    ["เปิดเตาอบ 180°C ตีเนยนิ่ม 100 กรัมกับน้ำตาล 120 กรัม", "ใส่ไข่และวานิลลา ตามด้วยแป้ง 180 กรัมและผงฟูครึ่งช้อนชา", "ใส่ช็อกโกแลตสับ ปั้นเป็นก้อน", "วางห่าง ๆ อบ 10–12 นาที พอเย็นจะแข็งตัว"]),
  r("banana_bread", "both", "american", "dessert", 70, "Banana bread", "บานาน่าเบรด",
    "banana; flour; egg; butter|oil; sugar|honey", "baking_powder cinnamon chocolate peanuts", "",
    ["Heat the oven to 175°C. Mash 3 very ripe bananas.", "Mix in 75 g melted butter, 1 egg, 100 g sugar and a little cinnamon.", "Fold in 190 g flour and 1 tsp baking powder.", "Bake in a loaf tin 50–60 minutes until a skewer comes out clean."],
    ["เปิดเตาอบ 175°C บดกล้วยสุกงอม 3 ลูก", "ผสมเนยละลาย 75 กรัม ไข่ 1 ฟอง น้ำตาล 100 กรัม และอบเชยเล็กน้อย", "ตะล่อมแป้ง 190 กรัมและผงฟู 1 ช้อนชา", "อบในพิมพ์ขนมปัง 50–60 นาทีจนเสียบไม้แล้วไม่ติด"]),
  r("french_toast", "both", "american", "breakfast", 15, "French toast", "เฟรนช์โทสต์",
    "bread; egg; milk", "butter cinnamon honey berries sugar banana", "",
    ["Whisk eggs, milk and a pinch of cinnamon.", "Soak thick slices of bread (a day old is best) for 20 seconds each side.", "Fry in butter until golden on both sides.", "Serve with honey, berries or banana."],
    ["ตีไข่ นม และอบเชยหยิบมือ", "จุ่มขนมปังแผ่นหนา (ขนมปังเก่า 1 วันดีที่สุด) ด้านละ 20 วินาที", "ทอดกับเนยจนเหลืองทั้งสองด้าน", "เสิร์ฟกับน้ำผึ้ง เบอร์รี่ หรือกล้วย"]),
  r("mug_cake", "both", "american", "dessert", 5, "Chocolate mug cake", "เค้กในแก้ว",
    "flour; cocoa|chocolate; sugar; milk; oil|butter", "egg baking_powder vanilla", "",
    ["In a big mug mix 4 tbsp flour, 2 tbsp cocoa, 3 tbsp sugar and a pinch of baking powder.", "Stir in 3 tbsp milk and 2 tbsp oil until smooth.", "Microwave 60–90 seconds until risen but still moist.", "Leave 1 minute before eating."],
    ["ในแก้วมัคใบใหญ่ ผสมแป้ง 4 ช้อนโต๊ะ โกโก้ 2 ช้อนโต๊ะ น้ำตาล 3 ช้อนโต๊ะ และผงฟูเล็กน้อย", "ใส่นม 3 ช้อนโต๊ะและน้ำมัน 2 ช้อนโต๊ะ คนให้เนียน", "เข้าไมโครเวฟ 60–90 วินาทีจนฟูแต่ยังชุ่ม", "พัก 1 นาทีก่อนกิน"]),
  r("overnight_oats", "both", "american", "breakfast", 5, "Overnight oats", "โอ๊ตแช่ข้ามคืน",
    "oats; milk|yogurt", "berries banana honey peanut_butter cinnamon mango", "",
    ["Mix 50 g oats with 120 ml milk or yogurt in a jar.", "Add honey, cinnamon or peanut butter.", "Refrigerate overnight.", "Top with fruit in the morning."],
    ["ผสมข้าวโอ๊ต 50 กรัมกับนมหรือโยเกิร์ต 120 มล. ในขวดโหล", "ใส่น้ำผึ้ง อบเชย หรือเนยถั่ว", "แช่ตู้เย็นข้ามคืน", "ตอนเช้าโรยผลไม้"]),

  // ---- French, Italian and more ----
  r("crepes", "both", "french", "dessert", 25, "Crêpes", "เครป",
    "flour; egg; milk; butter", "sugar banana chocolate berries honey lime", "",
    ["Whisk 125 g flour, 2 eggs, 300 ml milk and a spoon of melted butter; rest 15 minutes.", "Cook very thin in a buttered pan, about 1 minute a side.", "Fill with banana and chocolate, berries, or sugar and lemon.", "Fold into quarters and serve warm."],
    ["ตีแป้ง 125 กรัม ไข่ 2 ฟอง นม 300 มล. และเนยละลายหนึ่งช้อน พัก 15 นาที", "ละเลงบาง ๆ บนกระทะทาเนย ด้านละราว 1 นาที", "ใส่ไส้กล้วยช็อกโกแลต เบอร์รี่ หรือน้ำตาลมะนาว", "พับเป็นสี่ เสิร์ฟอุ่น"]),
  r("chocolate_mousse", "both", "french", "dessert", 20, "Chocolate mousse", "มูสช็อกโกแลต",
    "chocolate; egg", "sugar cream berries", "",
    ["Melt 100 g dark chocolate and let it cool slightly.", "Separate 3 eggs; stir the yolks into the chocolate.", "Whisk the whites to soft peaks with a spoon of sugar and fold in gently.", "Chill for 2 hours. (Uses raw egg: not for pregnant women, young children or the elderly.)"],
    ["ละลายดาร์กช็อกโกแลต 100 กรัม พักให้อุ่นลง", "แยกไข่ 3 ฟอง ผสมไข่แดงกับช็อกโกแลต", "ตีไข่ขาวกับน้ำตาลหนึ่งช้อนจนตั้งยอดอ่อน ตะล่อมเบา ๆ", "แช่เย็น 2 ชั่วโมง (ใช้ไข่ดิบ ไม่เหมาะกับหญิงตั้งครรภ์ เด็กเล็ก และผู้สูงอายุ)"]),
  r("creme_caramel", "both", "french", "dessert", 60, "Crème caramel", "คาราเมลคัสตาร์ด",
    "egg; milk; sugar", "vanilla cream", "",
    ["Melt 100 g sugar to an amber caramel and pour into small dishes.", "Whisk 3 eggs with 400 ml warm milk, 50 g sugar and vanilla; strain over the caramel.", "Bake in a tray of hot water at 160°C for 35–40 minutes until just set.", "Chill, then turn out onto plates."],
    ["เคี่ยวน้ำตาล 100 กรัมจนเป็นคาราเมลสีอำพัน เทลงถ้วยเล็ก", "ตีไข่ 3 ฟองกับนมอุ่น 400 มล. น้ำตาล 50 กรัม และวานิลลา กรองใส่ถ้วย", "อบแบบน้ำร้อนที่ 160°C ราว 35–40 นาทีจนเซ็ตตัว", "แช่เย็นแล้วคว่ำใส่จาน"]),
  r("panna_cotta", "both", "italian", "dessert", 20, "Panna cotta with berries", "พานาคอตต้าเบอร์รี่",
    "cream|coconut_milk; milk; sugar; agar", "vanilla berries mango honey", "",
    ["Warm 300 ml cream and 100 ml milk with sugar and vanilla.", "Whisk in 1 tsp agar and boil for 1 minute (agar needs boiling to set).", "Pour into glasses and chill for 2 hours.", "Top with berries or mango."],
    ["อุ่นครีม 300 มล. นม 100 มล. น้ำตาล และวานิลลา", "ใส่ผงวุ้น 1 ช้อนชา ต้มเดือด 1 นาที (วุ้นต้องต้มเดือดถึงจะเซ็ต)", "เทใส่แก้ว แช่เย็น 2 ชั่วโมง", "โรยหน้าด้วยเบอร์รี่หรือมะม่วง"]),
  r("apple_turnovers", "both", "french", "dessert", 35, "Apple turnovers", "พายแอปเปิลพับ",
    "puff_pastry; apple; sugar", "cinnamon butter egg", "apple>banana,berries",
    ["Heat the oven to 200°C. Cook diced apple with sugar, butter and cinnamon for 5 minutes; cool.", "Cut pastry into squares and spoon apple onto one half.", "Fold into triangles, press the edges and brush with egg or milk.", "Bake 18–20 minutes until puffed and golden."],
    ["เปิดเตาอบ 200°C ผัดแอปเปิลหั่นเต๋ากับน้ำตาล เนย และอบเชย 5 นาที พักให้เย็น", "ตัดแป้งพัฟเป็นสี่เหลี่ยม ตักไส้วางครึ่งหนึ่ง", "พับเป็นสามเหลี่ยม กดขอบ ทาไข่หรือนม", "อบ 18–20 นาทีจนฟูเหลือง"]),
  r("fruit_smoothie", "both", "american", "snack", 5, "Fruit smoothie", "สมูทตี้ผลไม้",
    "banana|berries|mango; milk|yogurt", "honey oats peanut_butter", "",
    ["Put fruit (frozen is great) in a blender.", "Add milk or yogurt and a little honey.", "Add a spoon of oats or peanut butter to make it filling.", "Blend until smooth."],
    ["ใส่ผลไม้ (แช่แข็งยิ่งดี) ลงเครื่องปั่น", "เติมนมหรือโยเกิร์ตและน้ำผึ้งเล็กน้อย", "ใส่ข้าวโอ๊ตหรือเนยถั่วหนึ่งช้อนให้อิ่มท้อง", "ปั่นจนเนียน"]),
  r("nice_cream", "both", "american", "dessert", 5, "One-ingredient banana ice cream", "ไอศกรีมกล้วย",
    "banana", "cocoa peanut_butter berries honey", "",
    ["Slice ripe bananas and freeze for at least 4 hours.", "Blend the frozen slices, scraping down, until creamy like soft-serve.", "Blend in cocoa, peanut butter or berries if you like.", "Eat straight away or freeze 30 minutes for scoops."],
    ["หั่นกล้วยสุก แช่แข็งอย่างน้อย 4 ชั่วโมง", "ปั่นกล้วยแช่แข็ง ปาดข้างโถเป็นระยะ จนเนียนเหมือนซอฟต์เสิร์ฟ", "ใส่โกโก้ เนยถั่ว หรือเบอร์รี่ถ้าชอบ", "กินทันที หรือแช่แข็งต่อ 30 นาทีแล้วตักเป็นลูก"]),
  r("choc_truffles", "both", "french", "dessert", 20, "Chocolate truffles", "ทรัฟเฟิลช็อกโกแลต",
    "chocolate; cream|coconut_milk", "cocoa butter vanilla", "",
    ["Heat 100 ml cream until steaming and pour over 200 g chopped chocolate.", "Stir until smooth; chill 2 hours until firm.", "Scoop and roll into balls with cold hands.", "Roll in cocoa powder."],
    ["อุ่นครีม 100 มล. จนมีไอ เทราดช็อกโกแลตสับ 200 กรัม", "คนจนเนียน แช่เย็น 2 ชั่วโมงจนแข็ง", "ตักแล้วปั้นเป็นลูกกลมด้วยมือที่เย็น", "คลุกผงโกโก้"]),
  r("mango_lassi", "both", "indian", "snack", 5, "Mango lassi", "มะม่วงลัสซี่",
    "mango; yogurt", "milk honey sugar", "mango>banana,berries",
    ["Put chopped ripe mango in a blender.", "Add yogurt, a splash of milk and honey to taste.", "Blend until smooth and frothy.", "Serve cold."],
    ["ใส่มะม่วงสุกหั่นลงเครื่องปั่น", "เติมโยเกิร์ต นมเล็กน้อย และน้ำผึ้งตามชอบ", "ปั่นจนเนียนเป็นฟอง", "เสิร์ฟเย็น ๆ"]),
];
