import { r } from "./types";

// British, Italian, French, Spanish, Greek and Middle Eastern home cooking. Amounts for two people.
export const EUROPE = [
  // ---- British ----
  r("full_english", "uk", "british", "breakfast", 25, "Full English breakfast", "อาหารเช้าแบบอังกฤษ",
    "egg; sausage|bacon; bread|potato", "tomato mushroom baked_beans butter", "",
    ["Grill or fry the sausages first (they take longest), then the bacon.", "Fry halved tomatoes and mushrooms in the same pan.", "Warm the beans; fry or poach the eggs; toast the bread.", "Serve everything together while hot."],
    ["ย่างหรือทอดไส้กรอกก่อน (ใช้เวลานานสุด) ตามด้วยเบคอน", "ทอดมะเขือเทศผ่าครึ่งและเห็ดในกระทะเดียวกัน", "อุ่นถั่วอบ ทอดหรือต้มไข่ ปิ้งขนมปัง", "จัดทุกอย่างรวมกัน เสิร์ฟร้อน ๆ"]),
  r("beans_on_toast", "uk", "british", "breakfast", 8, "Beans on toast", "ถั่วอบบนขนมปังปิ้ง",
    "baked_beans; bread", "cheese butter pepper egg", "",
    ["Warm the beans gently in a pan.", "Toast and butter the bread.", "Spoon the beans over the toast.", "Grate cheese on top or add a fried egg."],
    ["อุ่นถั่วอบในหม้อไฟอ่อน", "ปิ้งขนมปังแล้วทาเนย", "ตักถั่วราดบนขนมปัง", "ขูดชีสโรยหรือเพิ่มไข่ดาว"]),
  r("cottage_pie", "uk", "british", "main", 60, "Cottage pie", "คอทเทจพาย (พายเนื้อหน้ามันบด)",
    "beef|lamb|pork_mince; potato; onion; stock|soy_sauce", "carrot peas butter milk cheese dried_herbs tinned_tomato", "",
    ["Brown the mince with onion and carrot; add stock, herbs and a spoon of tomato; simmer 20 minutes.", "Boil potatoes and mash with butter and milk.", "Put the mince in a dish, spread the mash on top and rough it up with a fork; add cheese.", "Bake at 200°C for 20–25 minutes until golden. (With lamb it is a shepherd's pie.)"],
    ["ผัดเนื้อสับกับหอมใหญ่และแครอทจนเหลือง เติมน้ำซุป สมุนไพร และมะเขือเทศหนึ่งช้อน เคี่ยว 20 นาที", "ต้มมันฝรั่ง บดกับเนยและนม", "ใส่เนื้อลงถาด ปาดมันบดด้านบน ใช้ส้อมขีดให้เป็นลาย โรยชีส", "อบ 200°C ราว 20–25 นาทีจนเหลือง (ถ้าใช้เนื้อแกะเรียกว่าเชพเพิร์ดพาย)"]),
  r("fish_and_chips", "uk", "british", "main", 45, "Oven fish and chips", "ฟิชแอนด์ชิปส์แบบอบ",
    "fish; potato; flour|breadcrumbs; oil|olive_oil", "peas lime mayonnaise vinegar egg", "",
    ["Heat the oven to 220°C. Cut potatoes into chips, toss with oil and salt and roast 35–40 minutes.", "Dust the fish in flour, dip in egg and coat in breadcrumbs.", "Bake the fish on an oiled tray for the last 12–15 minutes.", "Serve with peas, a squeeze of lemon and vinegar on the chips."],
    ["เปิดเตาอบ 220°C หั่นมันฝรั่งเป็นแท่ง คลุกน้ำมันและเกลือ อบ 35–40 นาที", "คลุกปลากับแป้ง จุ่มไข่ แล้วคลุกเกล็ดขนมปัง", "อบปลาบนถาดทาน้ำมันใน 12–15 นาทีสุดท้าย", "เสิร์ฟกับถั่วลันเตา บีบมะนาว และราดน้ำส้มสายชูบนมันฝรั่ง"]),
  r("bangers_and_mash", "uk", "british", "main", 35, "Sausages and mash with onion gravy", "ไส้กรอกกับมันบดราดเกรวี่หอมใหญ่",
    "sausage; potato; onion; butter|milk", "stock flour peas", "",
    ["Boil potatoes and mash with butter and milk.", "Fry or grill the sausages until browned all over and cooked through.", "Slowly soften sliced onions in butter, stir in a spoon of flour, then stock; simmer to a gravy.", "Pile the sausages on the mash and pour over the gravy."],
    ["ต้มมันฝรั่ง บดกับเนยและนม", "ทอดหรือย่างไส้กรอกจนเหลืองทั่วและสุกใน", "ผัดหอมใหญ่ซอยกับเนยช้า ๆ จนนิ่ม ใส่แป้งหนึ่งช้อน แล้วเติมน้ำซุป เคี่ยวเป็นเกรวี่", "วางไส้กรอกบนมันบด ราดเกรวี่"]),
  r("jacket_potato", "uk", "british", "main", 70, "Jacket potato", "มันฝรั่งอบทั้งเปลือก",
    "potato; cheese|baked_beans|tuna", "butter mayonnaise sweetcorn spring_onion", "",
    ["Prick large potatoes, rub with oil and salt.", "Bake at 200°C for about an hour until crisp outside (or microwave 8 minutes first to speed up).", "Split open and add butter.", "Fill with cheese and beans, or tuna mayo with sweetcorn."],
    ["จิ้มมันฝรั่งหัวใหญ่ให้ทั่ว ทาน้ำมันและเกลือ", "อบ 200°C ราว 1 ชั่วโมงจนเปลือกกรอบ (หรือเข้าไมโครเวฟ 8 นาทีก่อนเพื่อลดเวลา)", "ผ่ากลาง ใส่เนย", "ใส่ไส้ชีสกับถั่วอบ หรือทูน่ามายองเนสกับข้าวโพด"]),
  r("toad_in_the_hole", "uk", "british", "main", 45, "Toad in the hole", "ไส้กรอกอบในแป้งยอร์กเชียร์",
    "sausage; flour; egg; milk; oil|olive_oil", "onion dried_herbs", "",
    ["Heat the oven to 220°C. Whisk 100 g flour, 2 eggs and 250 ml milk; rest.", "Brown the sausages in a tin with a little oil in the oven for 10 minutes.", "Pour the batter around the sausages into the very hot fat.", "Bake 25 minutes without opening the door until risen and golden."],
    ["เปิดเตาอบ 220°C ตีแป้ง 100 กรัม ไข่ 2 ฟอง และนม 250 มล. พักไว้", "อบไส้กรอกกับน้ำมันเล็กน้อยในถาด 10 นาทีให้เหลือง", "เทแป้งรอบไส้กรอกลงในน้ำมันที่ร้อนจัด", "อบ 25 นาทีโดยไม่เปิดเตาจนฟูเหลือง"]),
  r("pea_and_ham_soup", "uk", "british", "soup", 30, "Pea and ham soup", "ซุปถั่วลันเตากับแฮม",
    "peas; ham|bacon; onion; stock", "potato mint butter cream", "",
    ["Soften onion (and a diced potato) in butter.", "Add stock and simmer 10 minutes, then the peas for 3 minutes.", "Blend until smooth.", "Stir in shredded ham and a little mint."],
    ["ผัดหอมใหญ่ (และมันฝรั่งหั่นเต๋า) กับเนยจนนิ่ม", "เติมน้ำซุป ต้ม 10 นาที ใส่ถั่วลันเตาอีก 3 นาที", "ปั่นจนเนียน", "ใส่แฮมฉีกและสะระแหน่เล็กน้อย"]),
  r("cauliflower_cheese", "uk", "british", "side", 35, "Cauliflower cheese", "กะหล่ำดอกอบชีส",
    "cauliflower|broccoli; cheese; milk; flour|cornflour; butter", "pepper breadcrumbs", "",
    ["Boil cauliflower florets for 5 minutes; drain into a dish.", "Melt butter, stir in flour, then whisk in milk to a smooth sauce.", "Stir in most of the cheese; pour over the cauliflower.", "Top with the rest of the cheese and bake at 200°C for 20 minutes."],
    ["ต้มกะหล่ำดอก 5 นาที สะเด็ดน้ำใส่ถาด", "ละลายเนย ใส่แป้ง แล้วค่อย ๆ ตีนมลงไปจนเป็นซอสเนียน", "ใส่ชีสส่วนใหญ่ ราดบนกะหล่ำดอก", "โรยชีสที่เหลือ อบ 200°C ราว 20 นาที"]),
  r("chicken_pie", "uk", "british", "main", 50, "Chicken and mushroom pie", "พายไก่เห็ด",
    "chicken; puff_pastry; mushroom|peas|carrot|sweetcorn; milk|cream", "flour stock onion butter egg", "",
    ["Fry diced chicken, onion and mushrooms in butter.", "Stir in a spoon of flour, then milk or cream and a little stock; simmer until thick.", "Put in a dish and cover with puff pastry; brush with egg.", "Bake at 200°C for 25 minutes until puffed."],
    ["ผัดไก่หั่นเต๋า หอมใหญ่ และเห็ดกับเนย", "ใส่แป้งหนึ่งช้อน ตามด้วยนมหรือครีมและน้ำซุปเล็กน้อย เคี่ยวจนข้น", "ใส่ถาด ปิดด้วยแป้งพัฟ ทาไข่", "อบ 200°C ราว 25 นาทีจนฟู"]),
  r("porridge", "uk", "british", "breakfast", 10, "Porridge", "ข้าวต้มข้าวโอ๊ต (พอร์ริดจ์)",
    "oats; milk", "honey banana berries cinnamon sugar peanut_butter", "",
    ["Put 50 g oats and 300 ml milk (or half water) in a pan.", "Simmer, stirring, for 4–5 minutes until creamy.", "Add a pinch of salt.", "Top with honey, banana or berries."],
    ["ใส่ข้าวโอ๊ต 50 กรัมกับนม 300 มล. (หรือนมผสมน้ำ) ลงหม้อ", "ต้ม คนเรื่อย ๆ 4–5 นาทีจนข้นครีมมี่", "ใส่เกลือหยิบมือ", "โรยน้ำผึ้ง กล้วย หรือเบอร์รี่"]),
  r("egg_mayo_sandwich", "uk", "british", "snack", 15, "Egg mayonnaise sandwich", "แซนด์วิชไข่มายองเนส",
    "egg; mayonnaise; bread", "lettuce spring_onion pepper cucumber", "mayonnaise>yogurt",
    ["Boil eggs for 9 minutes, cool and peel.", "Mash with mayonnaise, pepper and chopped spring onion.", "Spread on bread with lettuce or cucumber.", "Cut into triangles."],
    ["ต้มไข่ 9 นาที แช่น้ำเย็น ปอกเปลือก", "บดกับมายองเนส พริกไทย และต้นหอมซอย", "ทาบนขนมปัง ใส่ผักกาดหรือแตงกวา", "ตัดเป็นสามเหลี่ยม"]),
  r("coronation_chicken", "uk", "british", "main", 15, "Coronation chicken", "สลัดไก่กะหรี่ (โคโรเนชันชิกเก้น)",
    "chicken; mayonnaise|yogurt; curry_powder", "apple honey lettuce bread rice mango", "",
    ["Poach or use leftover cooked chicken; shred it.", "Mix mayonnaise (or yogurt) with curry powder and a little honey.", "Fold in the chicken and diced apple or mango.", "Serve in sandwiches, jacket potatoes or with rice salad."],
    ["ต้มไก่หรือใช้ไก่สุกที่เหลือ ฉีกเป็นชิ้น", "ผสมมายองเนส (หรือโยเกิร์ต) กับผงกะหรี่และน้ำผึ้งเล็กน้อย", "คลุกกับไก่และแอปเปิลหรือมะม่วงหั่นเต๋า", "เสิร์ฟในแซนด์วิช มันฝรั่งอบ หรือกับสลัดข้าว"]),
  r("kedgeree", "uk", "british", "main", 30, "Kedgeree", "เคดจีรี (ข้าวผัดกะหรี่ปลา)",
    "rice; fish|tuna; egg; curry_powder", "onion peas butter parsley coriander", "",
    ["Soften onion in butter with curry powder.", "Add cooked rice and flaked cooked fish (smoked haddock is traditional).", "Stir in peas and quartered boiled eggs.", "Finish with parsley or coriander."],
    ["ผัดหอมใหญ่กับเนยและผงกะหรี่จนนิ่ม", "ใส่ข้าวสวยและเนื้อปลาสุกแกะ (แบบดั้งเดิมใช้ปลาแฮดด็อกรมควัน)", "ใส่ถั่วลันเตาและไข่ต้มผ่าสี่", "โรยพาร์สลีย์หรือผักชี"]),
  r("scrambled_eggs", "uk", "british", "breakfast", 8, "Scrambled eggs on toast", "ไข่คนบนขนมปังปิ้ง",
    "egg; bread; butter|milk", "spinach mushroom tomato cheese pepper", "",
    ["Whisk eggs with a pinch of salt.", "Melt butter over low heat, add eggs and stir slowly with a spatula.", "Take off the heat while still a little wet; they keep cooking.", "Pile onto buttered toast; add spinach or mushrooms on the side."],
    ["ตีไข่กับเกลือหยิบมือ", "ละลายเนยไฟอ่อน ใส่ไข่แล้วคนช้า ๆ ด้วยพาย", "ยกลงตอนไข่ยังเปียกเล็กน้อย ไข่จะสุกต่อเอง", "ตักวางบนขนมปังปิ้งทาเนย เสิร์ฟกับผักโขมหรือเห็ด"]),
  r("sausage_casserole", "uk", "british", "main", 45, "Sausage and bean casserole", "สตูว์ไส้กรอกถั่ว",
    "sausage; tinned_tomato|tomato; onion; kidney_beans|baked_beans|potato", "carrot paprika dried_herbs stock garlic bell_pepper", "",
    ["Brown the sausages in a casserole; lift out.", "Soften onion, carrot and garlic; add paprika.", "Add tomatoes, beans, stock and the sausages; simmer 25 minutes.", "Serve with mash or crusty bread."],
    ["ทอดไส้กรอกในหม้อให้เหลือง ตักขึ้น", "ผัดหอมใหญ่ แครอท และกระเทียมจนนิ่ม ใส่ปาปริก้า", "ใส่มะเขือเทศ ถั่ว น้ำซุป และไส้กรอก เคี่ยว 25 นาที", "เสิร์ฟกับมันบดหรือขนมปัง"]),

  // ---- Italian ----
  r("carbonara", "both", "italian", "main", 20, "Spaghetti carbonara", "สปาเกตตีคาโบนารา",
    "pasta; egg; bacon|ham; cheese", "pepper garlic", "",
    ["Boil the pasta; keep a mug of the water.", "Fry bacon until crisp.", "Beat eggs with grated cheese and lots of black pepper.", "Off the heat, toss pasta with bacon, then the egg mix and a splash of pasta water until creamy (no cream needed)."],
    ["ต้มพาสต้า เก็บน้ำต้มไว้หนึ่งแก้ว", "ทอดเบคอนจนกรอบ", "ตีไข่กับชีสขูดและพริกไทยดำเยอะ ๆ", "ปิดไฟ คลุกเส้นกับเบคอน ตามด้วยไข่และน้ำต้มเส้นเล็กน้อยจนเป็นครีม (ไม่ต้องใช้ครีม)"]),
  r("aglio_olio", "both", "italian", "main", 15, "Garlic and chilli spaghetti", "สปาเกตตีกระเทียมพริก (อัลลิโอ โอลิโอ)",
    "pasta; garlic; olive_oil|oil", "chilli parsley cheese shrimp", "",
    ["Boil the pasta.", "Gently fry sliced garlic and chilli in plenty of olive oil until just golden.", "Toss in the pasta with a splash of pasta water.", "Finish with parsley (and prawns or cheese if you like)."],
    ["ต้มพาสต้า", "เจียวกระเทียมซอยกับพริกในน้ำมันมะกอกเยอะ ๆ ไฟอ่อนจนเหลืองอ่อน", "ใส่เส้นกับน้ำต้มเส้นเล็กน้อย คลุกให้เข้ากัน", "โรยพาร์สลีย์ (ใส่กุ้งหรือชีสก็ได้)"]),
  r("pesto_pasta", "both", "italian", "main", 15, "Basil pesto pasta", "พาสต้าซอสเพสโต้",
    "pasta; sweet_basil; cheese; olive_oil; garlic|garlic_powder", "peanuts tomato", "sweet_basil>thai_basil,parsley,spinach",
    ["Boil the pasta.", "Blend basil, garlic, cheese and a handful of nuts with olive oil into a paste.", "Toss the pasta with pesto and a splash of pasta water.", "Add cherry tomatoes if you have them."],
    ["ต้มพาสต้า", "ปั่นใบเบซิล กระเทียม ชีส และถั่วกำมือหนึ่งกับน้ำมันมะกอกจนเป็นซอส", "คลุกเส้นกับเพสโต้และน้ำต้มเส้นเล็กน้อย", "ใส่มะเขือเทศเชอร์รี่ถ้ามี"]),
  r("bolognese", "both", "italian", "main", 50, "Spaghetti bolognese", "สปาเกตตีโบโลเนส",
    "pasta; beef|pork_mince|lamb; tinned_tomato|tomato; onion", "carrot celery garlic dried_herbs cheese stock", "",
    ["Soften chopped onion, carrot and celery in oil; add garlic.", "Brown the mince, then add tomatoes, herbs and a little stock.", "Simmer at least 30 minutes until rich.", "Toss with pasta and top with cheese."],
    ["ผัดหอมใหญ่ แครอท และคื่นฉ่ายสับกับน้ำมันจนนิ่ม ใส่กระเทียม", "ใส่เนื้อสับผัดจนเหลือง เติมมะเขือเทศ สมุนไพร และน้ำซุปเล็กน้อย", "เคี่ยวอย่างน้อย 30 นาทีจนเข้มข้น", "คลุกกับเส้น โรยชีส"]),
  r("risotto", "both", "italian", "main", 35, "Mushroom risotto", "ริซอตโตเห็ด",
    "rice; mushroom|peas|pumpkin|spinach; onion; stock", "cheese butter garlic dried_herbs", "",
    ["Soften onion and garlic in butter; fry the mushrooms.", "Stir in the rice for 1 minute.", "Add hot stock a ladle at a time, stirring, for about 18 minutes until creamy but with a little bite.", "Beat in cheese and a knob of butter; rest 2 minutes."],
    ["ผัดหอมใหญ่และกระเทียมกับเนยจนนิ่ม ใส่เห็ดผัด", "ใส่ข้าวผัด 1 นาที", "ค่อย ๆ เติมน้ำซุปร้อนทีละทัพพี คนตลอดราว 18 นาทีจนข้นแต่เม็ดข้าวยังมีเนื้อ", "ใส่ชีสและเนย คนแรง ๆ พัก 2 นาที"]),
  r("minestrone", "both", "italian", "soup", 35, "Minestrone", "ซุปมิเนสโตรเน",
    "tinned_tomato|tomato; carrot|celery|courgette|cabbage; pasta|kidney_beans; stock", "onion garlic cheese dried_herbs spinach potato", "",
    ["Soften onion, carrot and celery in olive oil.", "Add tomatoes, stock and diced vegetables; simmer 15 minutes.", "Add small pasta or beans and cook 10 minutes more.", "Serve with grated cheese and bread."],
    ["ผัดหอมใหญ่ แครอท และคื่นฉ่ายกับน้ำมันมะกอก", "ใส่มะเขือเทศ น้ำซุป และผักหั่นเต๋า ต้ม 15 นาที", "ใส่พาสต้าเส้นเล็กหรือถั่ว ต้มต่อ 10 นาที", "เสิร์ฟกับชีสขูดและขนมปัง"]),
  r("tortilla_pizza", "both", "italian", "snack", 15, "Quick tortilla pizza", "พิซซ่าแผ่นแป้งตอร์ติญ่า",
    "tortillas|bread; tinned_tomato|ketchup|tomato; cheese", "ham mushroom bell_pepper dried_herbs sausage sweetcorn onion", "",
    ["Heat the oven to 220°C (or use a frying pan with a lid).", "Spread tomato over the tortilla and add herbs.", "Scatter cheese and toppings.", "Bake 6–8 minutes until bubbling and crisp."],
    ["เปิดเตาอบ 220°C (หรือใช้กระทะมีฝาปิด)", "ทาซอสมะเขือเทศบนแผ่นแป้ง โรยสมุนไพร", "โรยชีสและท็อปปิ้ง", "อบ 6–8 นาทีจนชีสเดือดและขอบกรอบ"]),
  r("caprese", "both", "italian", "salad", 5, "Tomato and mozzarella salad", "สลัดคาเปรเซ่",
    "tomato; cheese; olive_oil", "sweet_basil dried_herbs pepper bread", "",
    ["Slice ripe tomatoes and mozzarella.", "Arrange alternately on a plate.", "Scatter with basil, salt and pepper.", "Drizzle with good olive oil."],
    ["หั่นมะเขือเทศสุกและชีสมอสซาเรลลา", "เรียงสลับกันบนจาน", "โรยใบเบซิล เกลือ และพริกไทย", "ราดน้ำมันมะกอกดี ๆ"]),
  r("pasta_al_forno", "both", "italian", "main", 40, "Baked pasta", "พาสต้าอบชีส",
    "pasta; tinned_tomato|tomato; cheese", "sausage beef spinach onion garlic dried_herbs", "",
    ["Boil short pasta for 2 minutes less than the packet says.", "Make a quick tomato sauce with onion and garlic (add sausage or mince if you have it).", "Mix pasta with sauce, put in a dish and cover with cheese.", "Bake at 200°C for 20 minutes until golden."],
    ["ต้มพาสต้าเส้นสั้นน้อยกว่าเวลาบนซอง 2 นาที", "ทำซอสมะเขือเทศเร็ว ๆ กับหอมใหญ่และกระเทียม (ใส่ไส้กรอกหรือเนื้อสับถ้ามี)", "คลุกเส้นกับซอส ใส่ถาด โรยชีส", "อบ 200°C ราว 20 นาทีจนเหลือง"]),
  r("chicken_cacciatore", "both", "italian", "main", 45, "Chicken cacciatore", "ไก่ตุ๋นมะเขือเทศแบบอิตาเลียน",
    "chicken; tinned_tomato|tomato; onion", "bell_pepper mushroom dried_herbs garlic olive_oil", "",
    ["Brown chicken pieces in olive oil; lift out.", "Soften onion, peppers and mushrooms with garlic.", "Add tomatoes, herbs and the chicken; simmer covered 30 minutes.", "Serve with pasta, bread or mash."],
    ["ทอดไก่กับน้ำมันมะกอกให้เหลือง ตักขึ้น", "ผัดหอมใหญ่ พริกหวาน และเห็ดกับกระเทียมจนนิ่ม", "ใส่มะเขือเทศ สมุนไพร และไก่ ปิดฝาเคี่ยว 30 นาที", "เสิร์ฟกับพาสต้า ขนมปัง หรือมันบด"]),
  r("pasta_e_ceci", "both", "italian", "main", 25, "Pasta with chickpeas", "พาสต้าถั่วลูกไก่",
    "pasta; chickpeas; garlic", "tinned_tomato olive_oil dried_herbs chilli cheese spinach", "",
    ["Fry garlic and herbs in olive oil; add chickpeas and a spoon of tomato.", "Add water or stock and small pasta; simmer until the pasta is done.", "Mash some chickpeas to thicken it.", "Finish with olive oil and cheese."],
    ["ผัดกระเทียมและสมุนไพรกับน้ำมันมะกอก ใส่ถั่วลูกไก่และมะเขือเทศหนึ่งช้อน", "เติมน้ำหรือน้ำซุปและพาสต้าเส้นเล็ก ต้มจนเส้นสุก", "บดถั่วบางส่วนให้น้ำข้น", "ราดน้ำมันมะกอก โรยชีส"]),
  r("tuna_pasta", "both", "italian", "main", 15, "Tuna pasta", "พาสต้าทูน่า",
    "pasta; tuna", "sweetcorn tomato mayonnaise tinned_tomato cheese onion chilli", "",
    ["Boil the pasta.", "Mix tuna with sweetcorn and mayonnaise for a cold pasta salad…", "…or warm tuna in a quick tomato sauce for a hot version.", "Toss with the pasta and top with cheese."],
    ["ต้มพาสต้า", "ผสมทูน่ากับข้าวโพดและมายองเนสเป็นสลัดพาสต้าเย็น…", "…หรืออุ่นทูน่าในซอสมะเขือเทศแบบเร็วเป็นเมนูร้อน", "คลุกกับเส้น โรยชีส"]),

  // ---- French ----
  r("cheese_omelette", "both", "french", "breakfast", 8, "French omelette", "ออมเล็ตแบบฝรั่งเศส",
    "egg; butter|oil", "cheese mushroom ham spinach parsley", "",
    ["Beat 3 eggs with a pinch of salt.", "Melt butter in a small pan over medium heat; pour in the eggs.", "Stir quickly while shaking the pan, then let it set for a few seconds.", "Add cheese or ham, fold into thirds and slide onto a plate."],
    ["ตีไข่ 3 ฟองกับเกลือหยิบมือ", "ละลายเนยในกระทะเล็กไฟกลาง เทไข่ลงไป", "คนเร็ว ๆ พลางเขย่ากระทะ แล้วปล่อยให้เซ็ตสักครู่", "ใส่ชีสหรือแฮม พับเป็นสามทบ เลื่อนลงจาน"]),
  r("croque_monsieur", "both", "french", "snack", 15, "Croque monsieur", "ครอกมงซิเออร์ (แซนด์วิชแฮมชีสอบ)",
    "bread; ham; cheese; butter", "milk flour egg", "",
    ["Make sandwiches with ham and cheese.", "Butter the outside and fry until golden on both sides.", "Top with more cheese (or a quick white sauce).", "Grill until bubbling. Add a fried egg for a croque madame."],
    ["ทำแซนด์วิชไส้แฮมและชีส", "ทาเนยด้านนอก ทอดจนเหลืองทั้งสองด้าน", "โรยชีสด้านบน (หรือราดซอสขาวแบบเร็ว)", "อบไฟบนจนชีสเดือด ใส่ไข่ดาวเป็นครอกมาดาม"]),
  r("ratatouille", "both", "french", "main", 45, "Ratatouille", "ราทาทูย",
    "aubergine|courgette; tomato|tinned_tomato; onion", "bell_pepper garlic dried_herbs olive_oil bread", "",
    ["Cut aubergine, courgette, peppers and onion into chunks.", "Fry in batches in olive oil until lightly browned.", "Add garlic, tomatoes and herbs; simmer gently 25 minutes.", "Good hot or cold, with bread, rice or pasta."],
    ["หั่นมะเขือยาว ซูกินี พริกหวาน และหอมใหญ่เป็นชิ้น", "ผัดทีละส่วนกับน้ำมันมะกอกจนเหลืองนิด ๆ", "ใส่กระเทียม มะเขือเทศ และสมุนไพร เคี่ยวไฟอ่อน 25 นาที", "กินร้อนหรือเย็นก็ได้ กับขนมปัง ข้าว หรือพาสต้า"]),
  r("french_onion_soup", "both", "french", "soup", 60, "French onion soup", "ซุปหัวหอมแบบฝรั่งเศส",
    "onion; stock; bread; cheese", "butter dried_herbs flour", "",
    ["Slice lots of onions and cook very slowly in butter for 40 minutes until deep brown and sweet.", "Stir in a spoon of flour, then hot stock and herbs; simmer 10 minutes.", "Pour into bowls and float toasted bread on top.", "Cover with cheese and grill until melted."],
    ["ซอยหอมใหญ่เยอะ ๆ ผัดกับเนยไฟอ่อนมาก 40 นาทีจนน้ำตาลเข้มและหวาน", "ใส่แป้งหนึ่งช้อน ตามด้วยน้ำซุปร้อนและสมุนไพร ต้ม 10 นาที", "ตักใส่ชาม วางขนมปังปิ้งด้านบน", "โรยชีส อบไฟบนจนชีสละลาย"]),
  r("chicken_bacon_mushroom", "both", "french", "main", 50, "Chicken with bacon and mushrooms", "ไก่ตุ๋นเบคอนเห็ด (แบบคอกโอแว็ง)",
    "chicken; mushroom; bacon; onion; stock", "garlic carrot dried_herbs flour butter", "",
    ["Brown chicken pieces with the bacon; lift out.", "Fry onion, carrot and mushrooms; stir in a spoon of flour.", "Add stock (a splash of red wine is traditional), herbs and the chicken.", "Simmer covered 35 minutes; serve with mash or bread."],
    ["ทอดไก่กับเบคอนให้เหลือง ตักขึ้น", "ผัดหอมใหญ่ แครอท และเห็ด ใส่แป้งหนึ่งช้อน", "เติมน้ำซุป (แบบดั้งเดิมใส่ไวน์แดง) สมุนไพร และไก่", "ปิดฝาเคี่ยว 35 นาที เสิร์ฟกับมันบดหรือขนมปัง"]),
  r("quiche", "both", "french", "main", 50, "Quiche", "คีช",
    "puff_pastry|flour; egg; cream|milk; bacon|ham|spinach|mushroom", "cheese onion", "",
    ["Line a tin with pastry and bake blind at 200°C for 10 minutes.", "Fry bacon and onion, or wilt spinach.", "Whisk 3 eggs with 250 ml cream or milk and cheese; add the filling.", "Pour into the case and bake at 180°C for 25–30 minutes until just set."],
    ["ปูแป้งในพิมพ์ อบเปล่า 200°C ราว 10 นาที", "ผัดเบคอนกับหอมใหญ่ หรือผัดผักโขมพอสลด", "ตีไข่ 3 ฟองกับครีมหรือนม 250 มล. และชีส ใส่ไส้", "เทลงพิมพ์ อบ 180°C ราว 25–30 นาทีจนเซ็ตตัว"]),

  // ---- Spanish ----
  r("tortilla_espanola", "both", "spanish", "main", 40, "Spanish omelette", "ทอร์ติยาสเปน (ไข่เจียวมันฝรั่ง)",
    "egg; potato; onion; olive_oil|oil", "bell_pepper spinach", "",
    ["Slice potatoes and onion thinly; cook gently in plenty of olive oil for 20 minutes until soft.", "Drain and mix with 5 beaten eggs; rest 10 minutes.", "Cook in a small pan over low heat until almost set.", "Flip onto a plate and slide back in for 2 minutes."],
    ["ฝานมันฝรั่งและหอมใหญ่บาง ๆ ผัดกับน้ำมันมะกอกเยอะ ๆ ไฟอ่อน 20 นาทีจนนุ่ม", "สะเด็ดน้ำมัน ผสมกับไข่ตี 5 ฟอง พัก 10 นาที", "ทอดในกระทะเล็กไฟอ่อนจนเกือบเซ็ต", "คว่ำลงจาน แล้วไถกลับลงกระทะอีก 2 นาที"]),
  r("patatas_bravas", "both", "spanish", "side", 45, "Patatas bravas", "มันฝรั่งบราวาส",
    "potato; paprika; tinned_tomato|ketchup|tomato; olive_oil|oil", "garlic mayonnaise chilli", "",
    ["Cube potatoes and roast with olive oil and salt at 220°C for 35 minutes.", "Make a sauce: fry garlic and paprika, add tomato and chilli; simmer 10 minutes.", "Pour the sauce over the crisp potatoes.", "Add a drizzle of garlic mayonnaise."],
    ["หั่นมันฝรั่งเต๋า อบกับน้ำมันมะกอกและเกลือที่ 220°C ราว 35 นาที", "ทำซอส ผัดกระเทียมกับปาปริก้า ใส่มะเขือเทศและพริก เคี่ยว 10 นาที", "ราดซอสบนมันฝรั่งกรอบ", "ราดมายองเนสกระเทียม"]),
  r("gambas_al_ajillo", "both", "spanish", "main", 10, "Garlic prawns", "กุ้งผัดกระเทียมน้ำมันมะกอก",
    "shrimp; garlic; olive_oil|oil", "chilli paprika parsley bread lime", "",
    ["Warm plenty of olive oil with sliced garlic and chilli.", "Add prawns and cook 2–3 minutes until pink.", "Sprinkle with paprika and parsley.", "Serve sizzling with bread to mop up the oil."],
    ["อุ่นน้ำมันมะกอกเยอะ ๆ กับกระเทียมซอยและพริก", "ใส่กุ้ง ผัด 2–3 นาทีจนเปลี่ยนสี", "โรยปาปริก้าและพาร์สลีย์", "เสิร์ฟร้อน ๆ กับขนมปังจิ้มน้ำมัน"]),
  r("paella", "both", "spanish", "main", 45, "Chicken and prawn paella", "ปาเอยา",
    "rice; chicken|shrimp|sausage|squid; paprika; stock", "peas bell_pepper tomato onion garlic lime", "",
    ["Brown chicken or sausage in a wide pan; add onion, garlic and peppers.", "Stir in rice and paprika, then hot stock and tomato.", "Simmer without stirring for 18 minutes; add prawns and peas for the last 5.", "Let a crust form on the bottom; rest and serve with lemon."],
    ["ทอดไก่หรือไส้กรอกในกระทะกว้าง ใส่หอมใหญ่ กระเทียม และพริกหวาน", "ใส่ข้าวและปาปริก้า ตามด้วยน้ำซุปร้อนและมะเขือเทศ", "ต้มโดยไม่คน 18 นาที ใส่กุ้งและถั่วลันเตาใน 5 นาทีสุดท้าย", "ปล่อยให้ก้นกระทะเกิดข้าวตังกรอบ พักแล้วเสิร์ฟกับมะนาว"]),

  // ---- Greek and Middle Eastern ----
  r("greek_salad", "both", "greek_middle_eastern", "salad", 10, "Greek salad", "สลัดกรีก",
    "tomato; cucumber; feta|cheese", "onion olive_oil dried_herbs bell_pepper lettuce", "",
    ["Cut tomatoes and cucumber into chunks.", "Add sliced red onion and pepper.", "Top with a slab of feta and dried oregano.", "Drizzle with olive oil."],
    ["หั่นมะเขือเทศและแตงกวาเป็นชิ้น", "ใส่หอมแดงฝรั่งและพริกหวานซอย", "วางชีสเฟต้าด้านบน โรยออริกาโน่", "ราดน้ำมันมะกอก"]),
  r("hummus", "both", "greek_middle_eastern", "snack", 10, "Hummus", "ฮัมมุส",
    "chickpeas; lime; garlic|garlic_powder; olive_oil|oil", "cumin paprika peanut_butter bread", "",
    ["Drain the chickpeas, keeping some liquid.", "Blend with lemon juice, garlic, olive oil and a spoon of tahini (or peanut butter).", "Loosen with the chickpea liquid until very smooth.", "Top with paprika and olive oil; serve with bread or vegetables."],
    ["สะเด็ดน้ำถั่วลูกไก่ เก็บน้ำไว้บางส่วน", "ปั่นกับน้ำมะนาว กระเทียม น้ำมันมะกอก และทาฮินี (หรือเนยถั่ว) หนึ่งช้อน", "เติมน้ำถั่วจนเนียนมาก", "โรยปาปริก้าและราดน้ำมันมะกอก เสิร์ฟกับขนมปังหรือผักสด"]),
  r("shakshuka", "both", "greek_middle_eastern", "breakfast", 25, "Shakshuka", "ชัคชูก้า (ไข่ในซอสมะเขือเทศ)",
    "egg; tinned_tomato|tomato; onion|bell_pepper", "cumin paprika garlic chilli feta bread coriander", "",
    ["Soften onion and peppers with garlic, cumin and paprika.", "Add tomatoes and simmer 10 minutes until thick.", "Make wells and crack in the eggs; cover and cook until the whites are set.", "Top with feta and herbs; serve with bread."],
    ["ผัดหอมใหญ่และพริกหวานกับกระเทียม ยี่หร่า และปาปริก้าจนนิ่ม", "ใส่มะเขือเทศ เคี่ยว 10 นาทีจนข้น", "ทำหลุมแล้วตอกไข่ลงไป ปิดฝาจนไข่ขาวสุก", "โรยเฟต้าและสมุนไพร เสิร์ฟกับขนมปัง"]),
  r("falafel", "both", "greek_middle_eastern", "main", 35, "Falafel", "ฟาลาเฟล",
    "chickpeas; onion|spring_onion; flour|breadcrumbs; cumin", "parsley coriander garlic tortillas yogurt lettuce tomato", "",
    ["Blitz drained chickpeas with onion, garlic, herbs and cumin to a coarse paste.", "Add a spoon of flour so it holds together; shape small patties.", "Shallow-fry until crisp on both sides.", "Serve in wraps with salad and yogurt sauce."],
    ["ปั่นถั่วลูกไก่ที่สะเด็ดน้ำกับหอมใหญ่ กระเทียม สมุนไพร และยี่หร่า ให้หยาบ ๆ", "ใส่แป้งหนึ่งช้อนให้จับตัว ปั้นเป็นแผ่นเล็ก", "ทอดน้ำมันน้อยจนกรอบทั้งสองด้าน", "เสิร์ฟในแผ่นแป้งกับผักสลัดและซอสโยเกิร์ต"]),
  r("chicken_shawarma", "both", "greek_middle_eastern", "main", 35, "Chicken shawarma wraps", "ชาวาร์มาไก่",
    "chicken; tortillas|bread; cumin|paprika|curry_powder", "yogurt lettuce tomato cucumber garlic lime onion", "",
    ["Marinate sliced chicken with spices, garlic, lemon and a spoon of yogurt.", "Cook in a hot pan or under the grill until charred.", "Mix yogurt with garlic for the sauce.", "Wrap with lettuce, tomato and cucumber."],
    ["หมักไก่หั่นกับเครื่องเทศ กระเทียม มะนาว และโยเกิร์ตหนึ่งช้อน", "ย่างในกระทะร้อนหรือเตาอบไฟบนจนเกรียม", "ผสมโยเกิร์ตกับกระเทียมเป็นซอส", "ห่อกับผักกาด มะเขือเทศ และแตงกวา"]),
  r("couscous_salad", "both", "greek_middle_eastern", "salad", 15, "Herby couscous salad", "สลัดคูสคูสสมุนไพร",
    "couscous; tomato|cucumber|bell_pepper; lime; olive_oil|oil", "mint parsley feta chickpeas onion", "",
    ["Pour boiling water or stock over the couscous, cover for 5 minutes, then fluff with a fork.", "Chop tomato, cucumber and peppers.", "Mix with lemon juice, olive oil and plenty of herbs.", "Add feta or chickpeas to make a meal of it."],
    ["เทน้ำเดือดหรือน้ำซุปลงบนคูสคูส ปิดฝา 5 นาที แล้วใช้ส้อมยีให้ร่วน", "หั่นมะเขือเทศ แตงกวา และพริกหวาน", "คลุกกับน้ำมะนาว น้ำมันมะกอก และสมุนไพรเยอะ ๆ", "ใส่เฟต้าหรือถั่วลูกไก่ให้อิ่มขึ้น"]),
  r("lentil_soup", "both", "greek_middle_eastern", "soup", 30, "Red lentil soup", "ซุปถั่วเลนทิลแดง",
    "lentils; onion; cumin|curry_powder; stock", "carrot garlic lime tinned_tomato olive_oil", "",
    ["Soften onion, carrot and garlic in olive oil with cumin.", "Add rinsed red lentils and stock.", "Simmer 20 minutes until the lentils collapse.", "Blend and finish with lemon juice."],
    ["ผัดหอมใหญ่ แครอท และกระเทียมกับน้ำมันมะกอกและยี่หร่า", "ใส่ถั่วเลนทิลแดงที่ล้างแล้วและน้ำซุป", "ต้ม 20 นาทีจนถั่วเปื่อย", "ปั่นให้เนียน บีบมะนาว"]),
  r("tzatziki", "both", "greek_middle_eastern", "snack", 10, "Tzatziki with bread", "ซัตซิกิ (ดิปโยเกิร์ตแตงกวา)",
    "yogurt; cucumber; garlic|garlic_powder", "mint olive_oil bread lime", "",
    ["Grate the cucumber and squeeze out the water.", "Mix with thick yogurt, crushed garlic and a pinch of salt.", "Add chopped mint and a drizzle of olive oil.", "Serve with warm bread or grilled meat."],
    ["ขูดแตงกวาแล้วบีบน้ำออก", "ผสมกับโยเกิร์ตข้น กระเทียมบด และเกลือหยิบมือ", "ใส่สะระแหน่สับและราดน้ำมันมะกอก", "เสิร์ฟกับขนมปังอุ่นหรือเนื้อย่าง"]),
  r("moussaka", "both", "greek_middle_eastern", "main", 75, "Aubergine and lamb bake", "มูซาก้า (มะเขือยาวอบเนื้อแกะ)",
    "aubergine; lamb|beef; tinned_tomato|tomato; onion", "cinnamon cheese milk flour garlic potato", "",
    ["Slice aubergines, brush with oil and roast at 200°C until soft.", "Brown mince with onion, garlic and cinnamon; add tomatoes and simmer 15 minutes.", "Layer aubergine and meat in a dish.", "Top with cheese sauce and bake 30 minutes until golden."],
    ["หั่นมะเขือยาว ทาน้ำมัน อบ 200°C จนนุ่ม", "ผัดเนื้อสับกับหอมใหญ่ กระเทียม และอบเชย ใส่มะเขือเทศ เคี่ยว 15 นาที", "เรียงมะเขือยาวสลับกับเนื้อในถาด", "ราดซอสชีส อบ 30 นาทีจนเหลือง"]),
  r("baba_ganoush", "both", "greek_middle_eastern", "snack", 40, "Smoky aubergine dip", "บาบากานูช (ดิปมะเขือยาวย่าง)",
    "aubergine; garlic|garlic_powder; lime; olive_oil|oil", "yogurt cumin parsley bread", "",
    ["Char whole aubergines over a flame or under a hot grill until collapsed.", "Scoop out the flesh and chop.", "Mix with garlic, lemon, olive oil and a spoon of yogurt or tahini.", "Top with parsley; serve with bread."],
    ["ย่างมะเขือยาวทั้งลูกบนไฟหรือเตาอบไฟบนจนไหม้และยุบ", "ขูดเนื้อออกมาสับ", "ผสมกับกระเทียม มะนาว น้ำมันมะกอก และโยเกิร์ตหรือทาฮินีหนึ่งช้อน", "โรยพาร์สลีย์ เสิร์ฟกับขนมปัง"]),
  r("kofta", "both", "greek_middle_eastern", "main", 30, "Lamb kofta", "โคฟต้าเนื้อแกะ",
    "lamb|beef; onion; cumin|curry_powder", "parsley mint coriander yogurt tortillas garlic tomato cucumber", "",
    ["Mix mince with grated onion, garlic, cumin, herbs and salt.", "Shape into fingers around skewers.", "Grill or pan-fry 8–10 minutes, turning.", "Serve with yogurt, salad and flatbread."],
    ["ผสมเนื้อสับกับหอมใหญ่ขูด กระเทียม ยี่หร่า สมุนไพร และเกลือ", "ปั้นเป็นแท่งรอบไม้เสียบ", "ย่างหรือทอด 8–10 นาที พลิกระหว่างย่าง", "เสิร์ฟกับโยเกิร์ต สลัด และขนมปังแผ่น"]),
];
