import { r } from "./types";

// Thai home cooking. Amounts in the method are for two people.
export const THAI = [
  r("tom_yum_goong", "th", "thai", "soup", 20, "Hot and sour prawn soup", "ต้มยำกุ้ง",
    "shrimp|fish|chicken|squid; lemongrass; lime; fish_sauce|soy_sauce", "galangal kaffir mushroom chilli tomato coriander milk", "lemongrass>ginger",
    ["Simmer bruised lemongrass, sliced galangal and torn lime leaves in 600 ml water for 5 minutes.", "Add mushrooms and tomato, then the prawns; cook just until pink.", "Off the heat, season with fish sauce, lime juice and crushed chillies. Add a splash of milk for the creamy version.", "Taste for a sour-salty-hot balance and top with coriander."],
    ["ต้มตะไคร้ทุบ ข่าหั่น และใบมะกรูดฉีกในน้ำ 600 มล. ราว 5 นาที", "ใส่เห็ดและมะเขือเทศ ตามด้วยกุ้ง ต้มพอกุ้งเปลี่ยนสี", "ปิดไฟ ปรุงด้วยน้ำปลา น้ำมะนาว และพริกขี้หนูบุบ ถ้าชอบแบบน้ำข้นเติมนมเล็กน้อย", "ชิมให้ได้รสเปรี้ยว เค็ม เผ็ด โรยผักชี"]),
  r("tom_jued", "th", "thai", "soup", 20, "Clear soup with tofu and pork", "ต้มจืดเต้าหู้หมูสับ",
    "pork_mince|chicken|shrimp; tofu|glass_noodles|cabbage; soy_sauce|fish_sauce|stock", "spring_onion coriander garlic pepper carrot cabbage", "",
    ["Season the mince with soy sauce and pepper, then roll into small balls.", "Bring stock or water to the boil with a crushed garlic clove.", "Drop in the pork balls, then tofu, cabbage or soaked glass noodles; simmer 5 minutes.", "Season with soy or fish sauce and finish with spring onion and coriander."],
    ["หมักหมูสับกับซีอิ๊วและพริกไทย ปั้นเป็นก้อนเล็ก ๆ", "ต้มน้ำซุปหรือน้ำเปล่ากับกระเทียมบุบให้เดือด", "ใส่หมูสับ ตามด้วยเต้าหู้ กะหล่ำ หรือวุ้นเส้นที่แช่น้ำแล้ว ต้ม 5 นาที", "ปรุงด้วยซีอิ๊วหรือน้ำปลา โรยต้นหอมและผักชี"]),
  r("red_curry", "th", "thai", "main", 30, "Red curry", "แกงเผ็ด",
    "chicken|pork|beef|shrimp|tofu; red_curry_paste; coconut_milk; fish_sauce|soy_sauce", "thai_eggplant thai_basil kaffir bell_pepper chilli pumpkin palm_sugar sugar rice", "red_curry_paste>green_curry_paste",
    ["Fry the curry paste in a few spoons of coconut cream until the oil splits out.", "Add the meat and stir until coated.", "Add the rest of the coconut milk, a little water and the vegetables; simmer 10 minutes.", "Season with fish sauce and a pinch of sugar; finish with basil and lime leaf."],
    ["ผัดพริกแกงกับหัวกะทิจนแตกมัน", "ใส่เนื้อสัตว์ ผัดให้เข้ากัน", "เติมกะทิที่เหลือ น้ำเล็กน้อย และผัก เคี่ยว 10 นาที", "ปรุงด้วยน้ำปลาและน้ำตาลเล็กน้อย ใส่โหระพาและใบมะกรูด"]),
  r("massaman", "th", "thai", "main", 60, "Massaman curry", "แกงมัสมั่น",
    "chicken|beef|lamb; massaman_paste; coconut_milk; potato", "onion peanuts tamarind palm_sugar sugar fish_sauce cinnamon rice", "massaman_paste>red_curry_paste,curry_powder",
    ["Fry the paste in coconut cream until fragrant.", "Add the meat, then the rest of the coconut milk and enough water to cover; simmer gently 30 minutes (beef longer).", "Add potato chunks, onion and peanuts; cook until the potatoes are tender.", "Balance with tamarind, palm sugar and fish sauce: sweet, sour and salty together."],
    ["ผัดพริกแกงกับหัวกะทิจนหอม", "ใส่เนื้อสัตว์ เติมกะทิที่เหลือและน้ำให้ท่วม เคี่ยวไฟอ่อน 30 นาที (เนื้อวัวนานกว่า)", "ใส่มันฝรั่ง หอมใหญ่ และถั่วลิสง ต้มจนมันฝรั่งนุ่ม", "ปรุงด้วยมะขามเปียก น้ำตาลปี๊บ และน้ำปลา ให้ได้รสหวาน เปรี้ยว เค็ม"]),
  r("panang", "th", "thai", "main", 25, "Panang curry", "พะแนง",
    "pork|chicken|beef; red_curry_paste; coconut_milk; fish_sauce|soy_sauce", "kaffir palm_sugar sugar thai_basil peanuts peanut_butter chilli rice", "",
    ["Fry the curry paste in thick coconut cream until the oil rises.", "Add thinly sliced meat and cook through.", "Add a little more coconut milk to make a thick sauce; stir in crushed peanuts or a spoon of peanut butter.", "Season with fish sauce and palm sugar; finish with finely shredded lime leaves."],
    ["ผัดพริกแกงกับหัวกะทิข้น ๆ จนแตกมัน", "ใส่เนื้อสัตว์หั่นบาง ผัดจนสุก", "เติมกะทิอีกเล็กน้อยให้น้ำแกงข้น ใส่ถั่วลิสงบดหรือเนยถั่วหนึ่งช้อน", "ปรุงด้วยน้ำปลาและน้ำตาลปี๊บ โรยใบมะกรูดซอย"]),
  r("pad_thai", "th", "thai", "main", 25, "Pad thai", "ผัดไทย",
    "noodles; shrimp|tofu|chicken; egg; tamarind; fish_sauce|soy_sauce", "bean_sprouts peanuts spring_onion palm_sugar sugar dried_shrimp chilli garlic shallot lime", "tamarind>lime,vinegar; noodles>pasta",
    ["Soak rice noodles in warm water until bendy. Mix tamarind, palm sugar and fish sauce into a sauce.", "Fry garlic and shallot, then the prawns or tofu; push aside and scramble the egg.", "Add noodles and sauce with a splash of water; toss until soft and glossy.", "Fold in bean sprouts and spring onion; serve with peanuts, chilli and lime."],
    ["แช่เส้นในน้ำอุ่นจนนิ่ม ผสมมะขามเปียก น้ำตาลปี๊บ และน้ำปลาเป็นซอส", "เจียวกระเทียมกับหอมแดง ใส่กุ้งหรือเต้าหู้ ดันไว้ข้างกระทะ ตอกไข่ยี", "ใส่เส้นกับซอสและน้ำเล็กน้อย ผัดจนเส้นนุ่มเงา", "ใส่ถั่วงอกและกุยช่ายหรือต้นหอม เสิร์ฟกับถั่วลิสง พริกป่น และมะนาว"]),
  r("larb", "th", "thai", "salad", 15, "Spicy minced pork salad", "ลาบหมู",
    "pork_mince|chicken; lime; fish_sauce; shallot|onion", "mint coriander spring_onion chilli sticky_rice", "",
    ["Cook the mince in a dry pan with a splash of water until just done.", "Off the heat, season with fish sauce, lime juice and chilli flakes.", "Toss in sliced shallot, mint, coriander and spring onion.", "Add toasted ground rice if you have it; serve with sticky rice and raw veg."],
    ["รวนหมูสับในกระทะกับน้ำเล็กน้อยจนสุก", "ปิดไฟ ปรุงด้วยน้ำปลา น้ำมะนาว และพริกป่น", "ใส่หอมแดงซอย สะระแหน่ ผักชี และต้นหอม คลุกเบา ๆ", "โรยข้าวคั่วถ้ามี เสิร์ฟกับข้าวเหนียวและผักสด"]),
  r("tam_taeng", "th", "thai", "salad", 10, "Pounded cucumber salad", "ตำแตงกวา",
    "cucumber|carrot|cabbage; lime; fish_sauce; chilli; garlic", "tomato green_beans peanuts dried_shrimp palm_sugar sugar", "chilli>pepper",
    ["Pound garlic and chillies roughly in a mortar (or crush with a knife).", "Add palm sugar, lime juice and fish sauce and pound to dissolve.", "Add cucumber batons, tomato and beans; bruise lightly while turning with a spoon.", "Taste for sour-sweet-salty, then top with peanuts and dried shrimp."],
    ["โขลกกระเทียมกับพริกหยาบ ๆ", "ใส่น้ำตาลปี๊บ น้ำมะนาว และน้ำปลา โขลกให้ละลาย", "ใส่แตงกวาหั่นเป็นแท่ง มะเขือเทศ และถั่วฝักยาว โขลกเบา ๆ พลางคลุกด้วยช้อน", "ชิมให้ได้รสเปรี้ยว หวาน เค็ม โรยถั่วลิสงและกุ้งแห้ง"]),
  r("yum_woonsen", "th", "thai", "salad", 15, "Glass noodle salad", "ยำวุ้นเส้น",
    "glass_noodles; shrimp|pork_mince|squid; lime; fish_sauce", "onion tomato celery chilli coriander spring_onion sugar", "",
    ["Soak the glass noodles, then blanch for 1 minute and drain.", "Cook the mince or prawns in a little water.", "Mix lime juice, fish sauce, a pinch of sugar and chilli into a dressing.", "Toss everything with onion, tomato, celery and coriander while still warm."],
    ["แช่วุ้นเส้นให้นิ่ม ลวก 1 นาที สะเด็ดน้ำ", "รวนหมูสับหรือลวกกุ้งกับน้ำเล็กน้อย", "ผสมน้ำมะนาว น้ำปลา น้ำตาลเล็กน้อย และพริก เป็นน้ำยำ", "คลุกทุกอย่างกับหอมใหญ่ มะเขือเทศ คื่นฉ่าย และผักชี ขณะยังอุ่น"]),
  r("yum_kai_dao", "th", "thai", "salad", 15, "Fried egg salad", "ยำไข่ดาว",
    "egg; lime; fish_sauce; onion|shallot", "tomato chilli coriander celery sugar", "",
    ["Fry the eggs in hot oil until the edges are crisp and the yolks still soft.", "Cut each egg into pieces.", "Mix lime, fish sauce, sugar and chilli into a dressing.", "Toss with sliced onion, tomato, celery and coriander; spoon over the eggs."],
    ["ทอดไข่ดาวในน้ำมันร้อนจนขอบกรอบ ไข่แดงยังเยิ้ม", "หั่นไข่เป็นชิ้น", "ผสมน้ำมะนาว น้ำปลา น้ำตาล และพริก เป็นน้ำยำ", "คลุกกับหอมใหญ่ มะเขือเทศ คื่นฉ่าย และผักชี ราดบนไข่"]),
  r("pad_prik_gaeng", "th", "thai", "main", 15, "Red curry stir-fry with green beans", "ผัดพริกแกงถั่วฝักยาว",
    "pork|chicken|pork_mince; red_curry_paste; green_beans; oil|olive_oil", "kaffir fish_sauce sugar palm_sugar rice", "green_beans>bell_pepper,broccoli",
    ["Fry the curry paste in oil until fragrant (no coconut milk in this one).", "Add the meat and stir-fry until cooked.", "Add beans cut into short lengths with a splash of water; cook 2 minutes so they stay crisp.", "Season with fish sauce and sugar; finish with shredded lime leaves."],
    ["ผัดพริกแกงกับน้ำมันจนหอม (เมนูนี้ไม่ใส่กะทิ)", "ใส่เนื้อสัตว์ ผัดจนสุก", "ใส่ถั่วฝักยาวหั่นท่อนกับน้ำเล็กน้อย ผัด 2 นาทีให้ยังกรอบ", "ปรุงด้วยน้ำปลาและน้ำตาล โรยใบมะกรูดซอย"]),
  r("pad_pong_karee", "th", "thai", "main", 15, "Curry powder stir-fry with egg", "กุ้งผัดผงกะหรี่",
    "shrimp|squid|chicken; curry_powder; egg; milk|coconut_milk", "onion celery spring_onion oyster_sauce soy_sauce sugar chilli", "",
    ["Beat the egg with the milk and curry powder.", "Stir-fry onion, then the prawns or chicken until nearly cooked.", "Season with oyster or soy sauce and a pinch of sugar.", "Pour in the egg mix, stir gently until just set and creamy; add celery and spring onion."],
    ["ตีไข่กับนมและผงกะหรี่", "ผัดหอมใหญ่ ใส่กุ้งหรือไก่ ผัดจนเกือบสุก", "ปรุงด้วยซอสหอยนางรมหรือซีอิ๊วและน้ำตาลเล็กน้อย", "เทไข่ลงไป คนเบา ๆ จนไข่เริ่มเซ็ตตัวแต่ยังนุ่ม ใส่คื่นฉ่ายและต้นหอม"]),
  r("gai_pad_king", "th", "thai", "main", 15, "Chicken and ginger stir-fry", "ไก่ผัดขิง",
    "chicken|pork; ginger; oyster_sauce|soy_sauce", "mushroom onion spring_onion chilli garlic sugar rice", "",
    ["Cut ginger into fine matchsticks.", "Fry garlic, then the chicken until opaque.", "Add ginger, mushrooms and onion; stir-fry 2 minutes.", "Season with oyster sauce, soy and a little sugar; add spring onion and chilli."],
    ["ซอยขิงเป็นเส้นเล็ก", "เจียวกระเทียม ใส่ไก่ ผัดจนสุก", "ใส่ขิง เห็ด และหอมใหญ่ ผัด 2 นาที", "ปรุงด้วยซอสหอยนางรม ซีอิ๊ว น้ำตาลเล็กน้อย ใส่ต้นหอมและพริก"]),
  r("pad_pak_ruam", "th", "thai", "side", 10, "Mixed vegetable stir-fry", "ผัดผักรวม",
    "broccoli|cauliflower|chinese_kale|pak_choi|cabbage; carrot|mushroom|bell_pepper|sweetcorn|green_beans; garlic|garlic_powder; oyster_sauce|soy_sauce", "shrimp tofu pork sugar cornflour", "",
    ["Cut everything to a similar size; harder veg thinner.", "Fry garlic in hot oil, add carrots and broccoli first with a splash of water.", "Add the softer veg and stir-fry on high heat 2 minutes.", "Season with oyster sauce and a pinch of sugar; thicken with a little cornflour water if you like."],
    ["หั่นผักให้ขนาดใกล้กัน ผักแข็งหั่นบางกว่า", "เจียวกระเทียมในน้ำมันร้อน ใส่แครอทและบรอกโคลีก่อนพร้อมน้ำเล็กน้อย", "ใส่ผักที่นิ่มกว่า ผัดไฟแรง 2 นาที", "ปรุงด้วยซอสหอยนางรมและน้ำตาลเล็กน้อย ข้นด้วยแป้งละลายน้ำถ้าชอบ"]),
  r("moo_kratiem", "th", "thai", "main", 15, "Garlic pepper pork", "หมูทอดกระเทียม",
    "pork|chicken; garlic; fish_sauce|soy_sauce; oil|olive_oil", "pepper sugar rice cucumber", "",
    ["Marinate sliced pork with fish sauce, pepper and a pinch of sugar for 10 minutes.", "Fry lots of chopped garlic in oil until golden; lift out.", "Fry the pork in the garlic oil until browned and just cooked.", "Top with the crispy garlic; serve over rice with cucumber."],
    ["หมักหมูหั่นกับน้ำปลา พริกไทย และน้ำตาลเล็กน้อย 10 นาที", "เจียวกระเทียมสับเยอะ ๆ จนเหลือง ตักขึ้น", "ทอดหมูในน้ำมันกระเทียมจนเหลืองและสุก", "โรยกระเทียมเจียว เสิร์ฟกับข้าวสวยและแตงกวา"]),
  r("kai_palo", "th", "thai", "main", 45, "Five-spice braised eggs", "ไข่พะโล้",
    "egg; soy_sauce; sugar|palm_sugar|honey", "pork cinnamon garlic tofu coriander pepper", "",
    ["Hard-boil and peel the eggs.", "Caramelise sugar lightly in a pot, add crushed garlic, pepper and cinnamon.", "Add soy sauce, 600 ml water, the eggs and pork or tofu; simmer 30 minutes.", "The longer it sits the darker the eggs; serve with rice and coriander."],
    ["ต้มไข่ให้สุก ปอกเปลือก", "เคี่ยวน้ำตาลในหม้อให้เริ่มเป็นคาราเมล ใส่กระเทียม พริกไทย และอบเชย", "ใส่ซีอิ๊ว น้ำ 600 มล. ไข่ และหมูหรือเต้าหู้ เคี่ยว 30 นาที", "ยิ่งแช่นานไข่ยิ่งเข้มสวย เสิร์ฟกับข้าวสวยและผักชี"]),
  r("khao_man_gai", "th", "thai", "main", 45, "Hainanese chicken rice", "ข้าวมันไก่",
    "chicken; rice; ginger; garlic", "cucumber coriander soy_sauce chilli pandan spring_onion", "ginger>spring_onion",
    ["Poach the chicken with ginger and spring onion for 20 minutes; keep the stock.", "Fry garlic and ginger in a little oil, add washed rice and stir 1 minute.", "Cook the rice in the chicken stock (with a pandan leaf if you have one).", "Slice the chicken; serve with cucumber, coriander and a soy-ginger-chilli sauce."],
    ["ต้มไก่กับขิงและต้นหอม 20 นาที เก็บน้ำซุปไว้", "เจียวกระเทียมและขิงในน้ำมันเล็กน้อย ใส่ข้าวสารที่ซาวแล้ว ผัด 1 นาที", "หุงข้าวด้วยน้ำซุปไก่ (ใส่ใบเตยถ้ามี)", "หั่นไก่ เสิร์ฟกับแตงกวา ผักชี และน้ำจิ้มซีอิ๊วขิงพริก"]),
  r("kuay_teow_nam", "th", "thai", "main", 20, "Noodle soup", "ก๋วยเตี๋ยวน้ำ",
    "noodles; pork_mince|pork|chicken|fish; stock|fish_sauce|soy_sauce", "bean_sprouts spring_onion coriander garlic morning_glory pepper lime chilli", "noodles>instant_noodles,pasta",
    ["Make a quick broth: simmer stock or water with garlic and a little soy sauce.", "Cook the meat or meatballs in the broth.", "Blanch the noodles and bean sprouts; put in bowls.", "Ladle over the broth and meat; top with spring onion, coriander and pepper. Season at the table."],
    ["ทำน้ำซุปเร็ว ๆ ต้มน้ำซุปหรือน้ำเปล่ากับกระเทียมและซีอิ๊วเล็กน้อย", "ใส่เนื้อสัตว์หรือลูกชิ้นต้มในน้ำซุป", "ลวกเส้นและถั่วงอก ใส่ชาม", "ราดน้ำซุปและเนื้อ โรยต้นหอม ผักชี พริกไทย ปรุงเพิ่มตามชอบ"]),
  r("rad_na", "th", "thai", "main", 20, "Noodles in gravy with greens", "ราดหน้า",
    "noodles; pork|chicken|shrimp; chinese_kale|broccoli|pak_choi; cornflour; oyster_sauce|soy_sauce", "garlic sugar pepper vinegar", "noodles>pasta,instant_noodles",
    ["Fry the noodles with a little soy sauce until lightly charred; plate.", "Fry garlic and meat, add greens and 400 ml water.", "Season with oyster sauce, soy and sugar; thicken with cornflour mixed in water.", "Pour the gravy over the noodles; add pepper and vinegar with chilli at the table."],
    ["ผัดเส้นกับซีอิ๊วเล็กน้อยให้หอมไหม้นิด ๆ ตักใส่จาน", "เจียวกระเทียม ใส่เนื้อสัตว์ ใส่ผักและน้ำ 400 มล.", "ปรุงด้วยซอสหอยนางรม ซีอิ๊ว และน้ำตาล ข้นด้วยแป้งข้าวโพดละลายน้ำ", "ราดน้ำราดหน้าบนเส้น เติมพริกไทยและพริกน้ำส้มตามชอบ"]),
  r("mama_pad", "th", "thai", "main", 10, "Stir-fried instant noodles", "มาม่าผัด",
    "instant_noodles; egg|pork_mince|chicken|shrimp|sausage", "cabbage carrot onion spring_onion chilli oyster_sauce soy_sauce morning_glory", "",
    ["Boil the noodles for 1 minute less than the packet says; drain.", "Fry garlic, then the meat or egg.", "Add cabbage and carrot, then the noodles with half the seasoning sachet and a spoon of oyster sauce.", "Toss on high heat until dry and glossy; finish with spring onion."],
    ["ต้มเส้นน้อยกว่าเวลาที่ซองบอก 1 นาที สะเด็ดน้ำ", "เจียวกระเทียม ใส่เนื้อสัตว์หรือไข่", "ใส่กะหล่ำและแครอท ตามด้วยเส้น ผงปรุงครึ่งซอง และซอสหอยนางรมหนึ่งช้อน", "ผัดไฟแรงจนแห้งเงา โรยต้นหอม"]),
  r("yum_mama", "th", "thai", "salad", 10, "Spicy instant noodle salad", "ยำมาม่า",
    "instant_noodles; lime; fish_sauce", "pork_mince shrimp onion tomato celery chilli sugar squid", "",
    ["Cook the noodles and the minced pork or prawns together for 2 minutes; drain.", "Mix lime, fish sauce, a little sugar, chilli and a pinch of the noodle seasoning.", "Toss the noodles with the dressing, onion, tomato and celery.", "Eat straight away while warm."],
    ["ลวกเส้นพร้อมหมูสับหรือกุ้ง 2 นาที สะเด็ดน้ำ", "ผสมน้ำมะนาว น้ำปลา น้ำตาลเล็กน้อย พริก และผงปรุงนิดหน่อย", "คลุกเส้นกับน้ำยำ หอมใหญ่ มะเขือเทศ และคื่นฉ่าย", "กินทันทีตอนยังอุ่น"]),
  r("khao_kluk_kapi", "th", "thai", "main", 20, "Shrimp paste fried rice", "ข้าวคลุกกะปิ",
    "rice; shrimp_paste; oil|olive_oil", "egg shallot lime chilli green_beans sugar pork dried_shrimp mango cucumber", "",
    ["Fry the shrimp paste in oil for 30 seconds to take off the rawness.", "Add cooked rice and toss until every grain is coated.", "Make a thin omelette and slice it; sweet-braise some pork if you have it.", "Serve with shallot, beans, sour mango or cucumber, dried shrimp and lime."],
    ["ผัดกะปิกับน้ำมัน 30 วินาทีให้หายกลิ่นดิบ", "ใส่ข้าวสวย คลุกให้ทั่วทุกเม็ด", "ทอดไข่แผ่นบาง ๆ แล้วซอย ถ้ามีหมูทำหมูหวานด้วย", "เสิร์ฟกับหอมแดง ถั่วฝักยาว มะม่วงเปรี้ยวหรือแตงกวา กุ้งแห้ง และมะนาว"]),
  r("gai_yang", "th", "thai", "main", 50, "Thai grilled chicken", "ไก่ย่าง",
    "chicken; garlic|garlic_powder; fish_sauce|soy_sauce", "coriander pepper honey sugar sticky_rice sweet_chilli_sauce lemongrass", "",
    ["Pound garlic, coriander stems and pepper; mix with fish sauce and a little honey.", "Marinate the chicken for at least 30 minutes.", "Grill or roast at 200°C for 30–35 minutes, turning once, until the juices run clear.", "Serve with sticky rice and sweet chilli sauce."],
    ["โขลกกระเทียม รากผักชี และพริกไทย ผสมน้ำปลาและน้ำผึ้งเล็กน้อย", "หมักไก่อย่างน้อย 30 นาที", "ย่างหรืออบ 200°C ราว 30–35 นาที กลับด้านครั้งหนึ่ง จนน้ำไก่ใส", "เสิร์ฟกับข้าวเหนียวและน้ำจิ้มไก่"]),
  r("moo_ping", "th", "thai", "main", 40, "Grilled pork skewers", "หมูปิ้ง",
    "pork; garlic|garlic_powder; soy_sauce|oyster_sauce; sugar|palm_sugar|honey", "coconut_milk coriander pepper sticky_rice", "",
    ["Slice pork thinly; mix with garlic, pepper, soy or oyster sauce, sugar and a splash of coconut milk.", "Leave for 30 minutes, then thread onto skewers.", "Grill or cook under a hot grill 8–10 minutes, brushing with the leftover marinade.", "Serve with sticky rice."],
    ["หั่นหมูบาง ๆ คลุกกระเทียม พริกไทย ซีอิ๊วหรือซอสหอยนางรม น้ำตาล และกะทิเล็กน้อย", "หมักไว้ 30 นาที แล้วเสียบไม้", "ย่างหรืออบไฟบน 8–10 นาที ทาน้ำหมักที่เหลือระหว่างย่าง", "เสิร์ฟกับข้าวเหนียว"]),
  r("gai_tod", "th", "thai", "main", 30, "Thai fried chicken", "ไก่ทอด",
    "chicken; flour|cornflour|glutinous_rice_flour; oil", "garlic pepper fish_sauce sweet_chilli_sauce sticky_rice", "",
    ["Marinate chicken with garlic, pepper and fish sauce for 20 minutes.", "Toss in flour mixed with a little rice flour for extra crunch.", "Fry at medium heat until cooked through, then turn up the heat for the last minute to crisp.", "Drain and serve with sweet chilli sauce."],
    ["หมักไก่กับกระเทียม พริกไทย และน้ำปลา 20 นาที", "คลุกแป้งผสมแป้งข้าวเหนียวเล็กน้อยให้กรอบ", "ทอดไฟกลางจนสุกใน แล้วเร่งไฟนาทีสุดท้ายให้กรอบ", "สะเด็ดน้ำมัน เสิร์ฟกับน้ำจิ้มไก่"]),
  r("pla_nueng_manao", "th", "thai", "main", 25, "Steamed fish with lime and chilli", "ปลานึ่งมะนาว",
    "fish; lime; garlic; fish_sauce", "chilli coriander celery sugar lemongrass", "",
    ["Steam the fish for 10–12 minutes (lemongrass underneath if you have it).", "Meanwhile mix lime juice, fish sauce, chopped garlic, chilli and a pinch of sugar with a splash of hot water.", "Pour the hot sauce over the fish.", "Top with coriander and celery leaves."],
    ["นึ่งปลา 10–12 นาที (รองด้วยตะไคร้ถ้ามี)", "ระหว่างนั้นผสมน้ำมะนาว น้ำปลา กระเทียมสับ พริก น้ำตาลเล็กน้อย และน้ำร้อนนิดหน่อย", "ราดน้ำซอสร้อน ๆ บนปลา", "โรยผักชีและใบคื่นฉ่าย"]),
  r("pla_rad_prik", "th", "thai", "main", 25, "Crispy fish with chilli sauce", "ปลาราดพริก",
    "fish; chilli; garlic; sugar|palm_sugar; fish_sauce", "tamarind flour shallot thai_basil", "chilli>sweet_chilli_sauce",
    ["Dust the fish with flour and fry until crisp; drain.", "Fry garlic, shallot and chilli until fragrant.", "Add sugar, fish sauce, tamarind and a splash of water; simmer to a sticky sauce.", "Pour over the fish and top with fried basil."],
    ["คลุกปลากับแป้ง ทอดจนกรอบ สะเด็ดน้ำมัน", "ผัดกระเทียม หอมแดง และพริกจนหอม", "ใส่น้ำตาล น้ำปลา มะขามเปียก และน้ำเล็กน้อย เคี่ยวจนข้นเหนียว", "ราดบนปลา โรยใบกะเพราหรือโหระพาทอด"]),
  r("pad_woonsen", "th", "thai", "main", 15, "Stir-fried glass noodles", "ผัดวุ้นเส้น",
    "glass_noodles; egg; cabbage|carrot|spring_onion|onion; soy_sauce|oyster_sauce", "pork_mince shrimp tomato pepper garlic mushroom", "",
    ["Soak the glass noodles for 10 minutes and cut shorter.", "Fry garlic and meat, push aside and scramble the egg.", "Add vegetables, then noodles with soy, oyster sauce and a splash of water.", "Toss until the noodles are clear and soft; finish with spring onion and pepper."],
    ["แช่วุ้นเส้น 10 นาที ตัดให้สั้นลง", "เจียวกระเทียม ใส่เนื้อสัตว์ ดันไว้ข้าง ตอกไข่ยี", "ใส่ผัก ตามด้วยวุ้นเส้น ซีอิ๊ว ซอสหอยนางรม และน้ำเล็กน้อย", "ผัดจนเส้นใสนุ่ม โรยต้นหอมและพริกไทย"]),
  r("jok", "th", "thai", "breakfast", 30, "Rice porridge with pork", "โจ๊กหมู",
    "rice; pork_mince|chicken; soy_sauce|fish_sauce", "ginger egg spring_onion pepper coriander", "",
    ["Simmer rice (or leftover cooked rice) in plenty of water, stirring, until broken down and creamy.", "Roll seasoned mince into small balls and drop them in; cook 5 minutes.", "Season with soy sauce.", "Crack in an egg if you like; top with ginger, spring onion and pepper."],
    ["ต้มข้าว (หรือข้าวสวยที่เหลือ) กับน้ำเยอะ ๆ คนเรื่อย ๆ จนเม็ดข้าวแตกข้น", "ปั้นหมูสับที่หมักแล้วเป็นก้อนเล็ก ใส่ลงไป ต้ม 5 นาที", "ปรุงด้วยซีอิ๊ว", "ตอกไข่ลงไปถ้าชอบ โรยขิงซอย ต้นหอม และพริกไทย"]),
  r("kai_toon", "th", "thai", "side", 20, "Steamed egg custard", "ไข่ตุ๋น",
    "egg; stock|fish_sauce|soy_sauce", "pork_mince shrimp spring_onion mushroom carrot", "",
    ["Beat eggs with the same volume of stock or water and a little fish sauce; strain for silkiness.", "Stir in minced pork, prawns or mushrooms.", "Steam over gentle heat for 12–15 minutes until just set.", "Top with spring onion and a drop of soy sauce."],
    ["ตีไข่กับน้ำซุปหรือน้ำในปริมาณเท่ากัน ปรุงน้ำปลาเล็กน้อย กรองให้เนียน", "ใส่หมูสับ กุ้ง หรือเห็ด", "นึ่งไฟอ่อน 12–15 นาทีจนไข่เซ็ตตัว", "โรยต้นหอมและซีอิ๊วนิดหน่อย"]),
  r("moo_manao", "th", "thai", "salad", 15, "Pork with lime and garlic", "หมูมะนาว",
    "pork; lime; garlic; fish_sauce", "chilli cabbage mint coriander sugar", "",
    ["Slice pork thinly and blanch until just cooked; plunge in cold water.", "Mix lime juice, fish sauce, chopped garlic, chilli and a little sugar.", "Arrange the pork on sliced cabbage.", "Pour over the dressing and top with mint and coriander."],
    ["หั่นหมูบาง ๆ ลวกพอสุก แช่น้ำเย็น", "ผสมน้ำมะนาว น้ำปลา กระเทียมสับ พริก และน้ำตาลเล็กน้อย", "จัดหมูบนกะหล่ำปลีซอย", "ราดน้ำจิ้ม โรยสะระแหน่และผักชี"]),
  r("neua_nam_man_hoi", "th", "thai", "main", 15, "Beef in oyster sauce", "เนื้อผัดน้ำมันหอย",
    "beef; oyster_sauce", "onion mushroom spring_onion garlic chilli bell_pepper sugar rice", "oyster_sauce>soy_sauce",
    ["Slice beef thinly across the grain and toss with a little oyster sauce.", "Stir-fry garlic, then the beef on very high heat for 1–2 minutes.", "Add onion, mushrooms and peppers; toss 1 minute.", "Add more oyster sauce and a pinch of sugar; finish with spring onion."],
    ["หั่นเนื้อบาง ๆ ขวางเสี้ยน คลุกซอสหอยนางรมเล็กน้อย", "เจียวกระเทียม ใส่เนื้อผัดไฟแรงมาก 1–2 นาที", "ใส่หอมใหญ่ เห็ด และพริกหวาน ผัด 1 นาที", "เติมซอสหอยนางรมและน้ำตาลเล็กน้อย ใส่ต้นหอม"]),
  r("pad_kana_moo", "th", "thai", "main", 12, "Chinese kale with pork", "คะน้าผัดหมู",
    "chinese_kale; pork|pork_mince|bacon; garlic; oyster_sauce|soy_sauce", "chilli sugar rice", "chinese_kale>broccoli,pak_choi",
    ["Slice the kale stems thinly and keep the leaves separate.", "Fry garlic and chilli, then the pork until browned.", "Add stems first with a splash of water, then the leaves.", "Season with oyster sauce and a little sugar; serve with rice."],
    ["หั่นก้านคะน้าบาง ๆ แยกใบไว้", "เจียวกระเทียมกับพริก ใส่หมูผัดจนเหลือง", "ใส่ก้านก่อนพร้อมน้ำเล็กน้อย แล้วตามด้วยใบ", "ปรุงด้วยซอสหอยนางรมและน้ำตาลเล็กน้อย เสิร์ฟกับข้าว"]),
  r("pad_tua_ngok", "th", "thai", "side", 8, "Bean sprouts with tofu", "ผัดถั่วงอกเต้าหู้",
    "bean_sprouts; garlic|garlic_powder; oyster_sauce|soy_sauce|fish_sauce", "tofu spring_onion shrimp", "",
    ["Fry cubes of tofu until golden.", "Add garlic, then the bean sprouts on the highest heat.", "Season quickly with oyster sauce.", "Take off the heat after 1 minute so the sprouts stay crunchy."],
    ["ทอดเต้าหู้หั่นเต๋าจนเหลือง", "ใส่กระเทียม ตามด้วยถั่วงอก ใช้ไฟแรงสุด", "ปรุงเร็ว ๆ ด้วยซอสหอยนางรม", "ยกลงภายใน 1 นาทีให้ถั่วงอกยังกรอบ"]),
  r("gai_hor_bai_toey", "th", "thai", "snack", 40, "Pandan-wrapped chicken", "ไก่ห่อใบเตย",
    "chicken; pandan; soy_sauce|oyster_sauce; garlic|garlic_powder", "coriander sugar sesame_oil pepper sweet_chilli_sauce", "",
    ["Marinate bite-sized chicken with garlic, coriander, soy, oyster sauce, sugar and sesame oil for 30 minutes.", "Wrap each piece tightly in a pandan leaf.", "Fry or bake at 200°C for 15 minutes until cooked through.", "Unwrap at the table and dip in sweet chilli sauce."],
    ["หมักไก่ชิ้นพอคำกับกระเทียม รากผักชี ซีอิ๊ว ซอสหอยนางรม น้ำตาล และน้ำมันงา 30 นาที", "ห่อไก่แต่ละชิ้นด้วยใบเตยให้แน่น", "ทอดหรืออบ 200°C ราว 15 นาทีจนสุก", "แกะกินพร้อมน้ำจิ้มไก่"]),
  r("khao_soi", "th", "thai", "main", 35, "Northern curry noodles", "ข้าวซอยไก่",
    "noodles; red_curry_paste|curry_powder; coconut_milk; chicken", "shallot lime spring_onion fish_sauce sugar", "noodles>instant_noodles,pasta",
    ["Fry curry paste and a spoon of curry powder in coconut cream.", "Add the chicken, then the rest of the coconut milk and water; simmer 20 minutes.", "Season with fish sauce and a little sugar.", "Pour over boiled noodles; top with a few fried noodles, shallot and lime."],
    ["ผัดพริกแกงกับผงกะหรี่หนึ่งช้อนในหัวกะทิ", "ใส่ไก่ เติมกะทิที่เหลือและน้ำ เคี่ยว 20 นาที", "ปรุงด้วยน้ำปลาและน้ำตาลเล็กน้อย", "ราดบนเส้นที่ลวกแล้ว โรยเส้นทอดกรอบ หอมแดง และบีบมะนาว"]),
  r("yum_talay", "th", "thai", "salad", 15, "Spicy seafood salad", "ยำทะเล",
    "squid|shrimp|fish; lime; fish_sauce; onion|shallot", "celery tomato chilli coriander sugar garlic", "",
    ["Blanch squid and prawns for 1 minute only so they stay tender.", "Mix lime, fish sauce, garlic, chilli and a pinch of sugar.", "Toss seafood with onion, tomato and celery.", "Pour over the dressing and top with coriander."],
    ["ลวกปลาหมึกและกุ้งแค่ 1 นาทีให้ยังนุ่ม", "ผสมน้ำมะนาว น้ำปลา กระเทียม พริก และน้ำตาลเล็กน้อย", "คลุกอาหารทะเลกับหอมใหญ่ มะเขือเทศ และคื่นฉ่าย", "ราดน้ำยำ โรยผักชี"]),
  r("moo_satay", "th", "thai", "snack", 45, "Satay with peanut sauce", "หมูสะเต๊ะ",
    "pork|chicken; curry_powder; coconut_milk", "peanuts peanut_butter sugar cucumber vinegar red_curry_paste bread", "",
    ["Marinate strips of meat with curry powder, sugar and coconut milk for 30 minutes; thread onto skewers.", "Grill 8–10 minutes, brushing with coconut milk.", "For the sauce, simmer coconut milk with red curry paste, peanut butter and sugar until thick.", "Serve with a quick cucumber relish: cucumber, vinegar, sugar and shallot."],
    ["หมักเนื้อหั่นเป็นเส้นกับผงกะหรี่ น้ำตาล และกะทิ 30 นาที เสียบไม้", "ย่าง 8–10 นาที ทากะทิระหว่างย่าง", "ทำน้ำจิ้ม เคี่ยวกะทิกับพริกแกงเผ็ด เนยถั่ว และน้ำตาลจนข้น", "เสิร์ฟกับอาจาด แตงกวา น้ำส้มสายชู น้ำตาล และหอมแดง"]),
  r("kai_look_keuy", "th", "thai", "side", 25, "Son-in-law eggs", "ไข่ลูกเขย",
    "egg; tamarind; palm_sugar|sugar; fish_sauce", "shallot chilli coriander", "tamarind>lime",
    ["Boil eggs for 7 minutes, peel and fry until blistered and golden.", "Fry sliced shallots until crisp; lift out.", "Simmer tamarind, palm sugar and fish sauce into a sticky sauce.", "Halve the eggs, pour over the sauce and top with shallots and chilli."],
    ["ต้มไข่ 7 นาที ปอกเปลือก ทอดจนผิวพองเหลือง", "เจียวหอมแดงซอยจนกรอบ ตักขึ้น", "เคี่ยวมะขามเปียก น้ำตาลปี๊บ และน้ำปลาจนข้นเหนียว", "ผ่าไข่ครึ่ง ราดซอส โรยหอมเจียวและพริก"]),
  r("khao_pad_american", "th", "thai", "main", 20, "American fried rice", "ข้าวผัดอเมริกัน",
    "rice; ketchup; egg; sausage|chicken|ham", "peas onion sweetcorn butter carrot", "ketchup>tinned_tomato",
    ["Fry onion in butter, add peas, corn and carrot.", "Add cooked rice and ketchup; toss until evenly red.", "Serve with fried chicken or sausage and a fried egg on top.", "A Thai café classic from the 1960s."],
    ["ผัดหอมใหญ่กับเนย ใส่ถั่วลันเตา ข้าวโพด และแครอท", "ใส่ข้าวสวยกับซอสมะเขือเทศ ผัดจนแดงทั่ว", "เสิร์ฟกับไก่ทอดหรือไส้กรอก และไข่ดาวด้านบน", "เมนูร้านกาแฟไทยยุค 60"]),
  r("fak_thong_pad_kai", "th", "thai", "side", 15, "Stir-fried pumpkin with egg", "ฟักทองผัดไข่",
    "pumpkin; egg; garlic|garlic_powder; oyster_sauce|soy_sauce|fish_sauce", "pork sugar", "pumpkin>sweet_potato,carrot",
    ["Peel and thinly slice the pumpkin.", "Fry garlic, add pumpkin with a splash of water and cover for 3 minutes.", "Push aside, scramble the eggs, then toss together.", "Season with oyster sauce and a pinch of sugar."],
    ["ปอกฟักทอง หั่นเป็นชิ้นบาง", "เจียวกระเทียม ใส่ฟักทองกับน้ำเล็กน้อย ปิดฝา 3 นาที", "ดันไว้ข้าง ตอกไข่ยี แล้วผัดรวมกัน", "ปรุงด้วยซอสหอยนางรมและน้ำตาลเล็กน้อย"]),
  r("pad_makuea_yao", "th", "thai", "main", 15, "Aubergine with basil", "ผัดมะเขือยาว",
    "aubergine; garlic; oyster_sauce|soy_sauce", "pork_mince thai_basil holy_basil chilli fish_sauce sugar", "aubergine>courgette",
    ["Cut aubergine into chunks; fry in a little oil until soft and golden.", "Add garlic, chilli and minced pork if using; stir-fry until cooked.", "Season with oyster sauce, soy and a pinch of sugar.", "Fold in a handful of basil and serve."],
    ["หั่นมะเขือยาวเป็นท่อน ผัดกับน้ำมันเล็กน้อยจนนุ่มเหลือง", "ใส่กระเทียม พริก และหมูสับถ้ามี ผัดจนสุก", "ปรุงด้วยซอสหอยนางรม ซีอิ๊ว และน้ำตาลเล็กน้อย", "ใส่โหระพากำมือหนึ่ง แล้วตักเสิร์ฟ"]),
  r("priew_wan", "th", "thai", "main", 20, "Sweet and sour stir-fry", "ผัดเปรี้ยวหวาน",
    "pork|chicken|shrimp|fish|tofu; tomato|ketchup; cucumber|onion|bell_pepper", "vinegar lime sugar ketchup spring_onion garlic", "",
    ["Fry garlic, then the meat or tofu until cooked.", "Add onion, cucumber, tomato and peppers; toss 2 minutes.", "Add ketchup, a little vinegar, sugar and a splash of water.", "Simmer 1 minute until glossy; adjust sweet and sour to taste."],
    ["เจียวกระเทียม ใส่เนื้อสัตว์หรือเต้าหู้ ผัดจนสุก", "ใส่หอมใหญ่ แตงกวา มะเขือเทศ และพริกหวาน ผัด 2 นาที", "ใส่ซอสมะเขือเทศ น้ำส้มสายชูเล็กน้อย น้ำตาล และน้ำนิดหน่อย", "เคี่ยว 1 นาทีจนเงา ปรุงรสเปรี้ยวหวานตามชอบ"]),
];
