import { r } from "./types";

// Indian, East and Southeast Asian, Mexican and American home cooking. Amounts for two people.
export const WORLD = [
  // ---- Indian ----
  r("chicken_curry", "both", "indian", "main", 45, "Everyday chicken curry", "แกงกะหรี่ไก่แบบอินเดีย",
    "chicken; curry_powder; onion; tinned_tomato|tomato", "garlic ginger yogurt coconut_milk coriander rice chilli", "",
    ["Fry chopped onion slowly until golden, then garlic and ginger.", "Add curry powder and fry 1 minute.", "Add chicken, tomatoes and a splash of water; simmer 25 minutes.", "Stir in yogurt or coconut milk off the heat; top with coriander."],
    ["ผัดหอมใหญ่สับไฟอ่อนจนเหลือง ใส่กระเทียมและขิง", "ใส่ผงกะหรี่ผัด 1 นาที", "ใส่ไก่ มะเขือเทศ และน้ำเล็กน้อย เคี่ยว 25 นาที", "ปิดไฟ ใส่โยเกิร์ตหรือกะทิ โรยผักชี"]),
  r("dal", "both", "indian", "main", 35, "Red lentil dal", "ดาล (แกงถั่วเลนทิล)",
    "lentils; onion|garlic; curry_powder|cumin", "tomato ginger coriander spinach chilli rice butter", "",
    ["Simmer rinsed lentils in water with a pinch of turmeric or curry powder for 20 minutes until soft.", "Fry onion, garlic, ginger and cumin in butter or oil until golden.", "Stir this into the lentils with chopped tomato.", "Season, add spinach if you have it, and serve with rice."],
    ["ต้มถั่วเลนทิลที่ล้างแล้วกับน้ำและผงกะหรี่เล็กน้อย 20 นาทีจนนุ่ม", "เจียวหอมใหญ่ กระเทียม ขิง และยี่หร่ากับเนยหรือน้ำมันจนเหลือง", "เทลงในถั่ว ใส่มะเขือเทศสับ", "ปรุงรส ใส่ผักโขมถ้ามี เสิร์ฟกับข้าว"]),
  r("chana_masala", "both", "indian", "main", 30, "Chickpea curry", "ชานามาซาลา (แกงถั่วลูกไก่)",
    "chickpeas; curry_powder; onion; tinned_tomato|tomato", "ginger garlic coriander spinach lime rice", "",
    ["Fry onion, garlic and ginger until soft.", "Add curry powder, then tomatoes; simmer 5 minutes.", "Add chickpeas and a splash of water; simmer 15 minutes, mashing a few.", "Finish with lemon and coriander."],
    ["ผัดหอมใหญ่ กระเทียม และขิงจนนิ่ม", "ใส่ผงกะหรี่ ตามด้วยมะเขือเทศ เคี่ยว 5 นาที", "ใส่ถั่วลูกไก่และน้ำเล็กน้อย เคี่ยว 15 นาที บดถั่วบางส่วน", "บีบมะนาว โรยผักชี"]),
  r("aloo_gobi", "both", "indian", "main", 35, "Potato and cauliflower curry", "อาลูโกบี (มันฝรั่งกะหล่ำดอกผัดเครื่องแกง)",
    "potato; cauliflower|broccoli; curry_powder|cumin", "onion tomato ginger garlic coriander peas", "",
    ["Cut potatoes and cauliflower into small pieces.", "Fry onion and spices in oil for 1 minute.", "Add vegetables and a splash of water; cover and cook 15–20 minutes until tender.", "Add tomato for the last 5 minutes and finish with coriander."],
    ["หั่นมันฝรั่งและกะหล่ำดอกเป็นชิ้นเล็ก", "ผัดหอมใหญ่และเครื่องเทศกับน้ำมัน 1 นาที", "ใส่ผักและน้ำเล็กน้อย ปิดฝา 15–20 นาทีจนนุ่ม", "ใส่มะเขือเทศใน 5 นาทีสุดท้าย โรยผักชี"]),
  r("saag_aloo", "both", "indian", "side", 25, "Spinach and potato", "ซากอาลู (ผักโขมกับมันฝรั่ง)",
    "spinach; potato; curry_powder|cumin", "onion garlic ginger chilli", "",
    ["Boil diced potatoes until just tender.", "Fry onion, garlic and spices.", "Add the potatoes and fry until the edges crisp.", "Stir in spinach until wilted."],
    ["ต้มมันฝรั่งหั่นเต๋าพอนุ่ม", "ผัดหอมใหญ่ กระเทียม และเครื่องเทศ", "ใส่มันฝรั่ง ผัดจนขอบกรอบ", "ใส่ผักโขม ผัดจนสลด"]),
  r("egg_curry", "both", "indian", "main", 30, "Egg curry", "แกงกะหรี่ไข่",
    "egg; onion; tinned_tomato|tomato; curry_powder", "coconut_milk garlic ginger coriander rice", "",
    ["Hard-boil and peel the eggs; score them lightly.", "Fry onion, garlic, ginger and curry powder.", "Add tomatoes (and coconut milk) and simmer 10 minutes.", "Add the eggs and simmer 5 minutes; serve with rice."],
    ["ต้มไข่ให้สุก ปอกเปลือก กรีดเบา ๆ", "ผัดหอมใหญ่ กระเทียม ขิง และผงกะหรี่", "ใส่มะเขือเทศ (และกะทิ) เคี่ยว 10 นาที", "ใส่ไข่ เคี่ยวต่อ 5 นาที เสิร์ฟกับข้าว"]),
  r("chicken_tikka", "both", "indian", "main", 40, "Oven chicken tikka", "ไก่ทิกก้าอบ",
    "chicken; yogurt; curry_powder|paprika", "lime garlic ginger onion cucumber rice tortillas", "",
    ["Mix yogurt with spices, garlic, ginger and lemon.", "Coat chunks of chicken and marinate 30 minutes (or overnight).", "Roast on a rack at 220°C for 20 minutes until charred at the edges.", "Serve with rice or flatbread and cucumber."],
    ["ผสมโยเกิร์ตกับเครื่องเทศ กระเทียม ขิง และมะนาว", "คลุกไก่หั่นชิ้น หมัก 30 นาที (หรือข้ามคืน)", "อบบนตะแกรงที่ 220°C ราว 20 นาทีจนขอบเกรียม", "เสิร์ฟกับข้าวหรือขนมปังแผ่นและแตงกวา"]),
  r("keema_peas", "both", "indian", "main", 30, "Keema with peas", "คีมา (เนื้อสับผัดเครื่องแกงกับถั่ว)",
    "beef|lamb|pork_mince; peas; onion; curry_powder", "tinned_tomato garlic ginger coriander rice", "",
    ["Fry onion until golden; add garlic, ginger and curry powder.", "Brown the mince.", "Add tomatoes and a splash of water; simmer 15 minutes.", "Stir in peas for the last 5 minutes."],
    ["ผัดหอมใหญ่จนเหลือง ใส่กระเทียม ขิง และผงกะหรี่", "ใส่เนื้อสับผัดจนเหลือง", "ใส่มะเขือเทศและน้ำเล็กน้อย เคี่ยว 15 นาที", "ใส่ถั่วลันเตาใน 5 นาทีสุดท้าย"]),
  r("veg_biryani", "both", "indian", "main", 45, "Vegetable biryani", "บิรยานีผัก",
    "rice; curry_powder; onion; carrot|peas|cauliflower|potato", "yogurt cinnamon coriander mint egg", "",
    ["Fry sliced onions until deep golden; set half aside.", "Add spices and vegetables; fry 3 minutes.", "Add washed rice and 1.5 times its volume of water; cover and cook on low for 15 minutes.", "Rest 10 minutes, fluff and top with the crispy onions and herbs."],
    ["เจียวหอมใหญ่ซอยจนเหลืองเข้ม แบ่งครึ่งไว้", "ใส่เครื่องเทศและผัก ผัด 3 นาที", "ใส่ข้าวสารที่ซาวแล้วและน้ำ 1.5 เท่าของข้าว ปิดฝาไฟอ่อน 15 นาที", "พัก 10 นาที ยีให้ร่วน โรยหอมเจียวและสมุนไพร"]),
  r("raita", "both", "indian", "side", 5, "Cucumber raita", "ไรตา (โยเกิร์ตแตงกวา)",
    "yogurt; cucumber", "cumin mint coriander", "",
    ["Grate or finely dice cucumber.", "Mix with yogurt and a pinch of salt.", "Add toasted cumin and mint.", "Serve cold with curries."],
    ["ขูดหรือหั่นแตงกวาเต๋าเล็ก", "ผสมกับโยเกิร์ตและเกลือหยิบมือ", "ใส่ยี่หร่าคั่วและสะระแหน่", "เสิร์ฟเย็น ๆ คู่กับแกง"]),
  r("prawn_curry", "both", "indian", "main", 25, "Coconut prawn curry", "แกงกะหรี่กุ้งกะทิ",
    "shrimp|fish; coconut_milk; curry_powder; onion", "tomato garlic ginger lime coriander rice", "",
    ["Soften onion with garlic and ginger.", "Add curry powder and tomato; cook 3 minutes.", "Pour in coconut milk and simmer 5 minutes.", "Add prawns and cook 3 minutes until pink; finish with lime."],
    ["ผัดหอมใหญ่กับกระเทียมและขิงจนนิ่ม", "ใส่ผงกะหรี่และมะเขือเทศ ผัด 3 นาที", "เติมกะทิ เคี่ยว 5 นาที", "ใส่กุ้ง ต้ม 3 นาทีจนสุก บีบมะนาว"]),

  // ---- Chinese ----
  r("kung_pao_chicken", "both", "chinese", "main", 20, "Kung pao chicken", "ไก่ผัดพริกแห้งเสฉวน (กงเปาไก่)",
    "chicken; peanuts; chilli; soy_sauce", "vinegar sugar spring_onion garlic ginger cornflour", "peanuts>peanut_butter",
    ["Toss diced chicken with soy sauce and cornflour.", "Fry dried or fresh chillies briefly, then the chicken until golden.", "Add garlic, ginger and a sauce of soy, vinegar and sugar.", "Toss in peanuts and spring onion."],
    ["คลุกไก่หั่นเต๋ากับซีอิ๊วและแป้งข้าวโพด", "ผัดพริกแห้งหรือพริกสดสักครู่ ใส่ไก่ผัดจนเหลือง", "ใส่กระเทียม ขิง และซอสซีอิ๊ว น้ำส้มสายชู น้ำตาล", "ใส่ถั่วลิสงและต้นหอม"]),
  r("mapo_tofu", "both", "chinese", "main", 20, "Mapo tofu", "มาโผโต้วฟู (เต้าหู้ผัดหมูสับเผ็ด)",
    "tofu; pork_mince|beef; chilli|gochujang; soy_sauce", "garlic ginger spring_onion cornflour sesame_oil", "",
    ["Fry the mince until crisp, then garlic, ginger and chilli paste.", "Add a splash of water or stock and soy sauce.", "Slide in cubed tofu and simmer gently 5 minutes.", "Thicken with cornflour water; finish with spring onion."],
    ["ผัดหมูสับจนกรอบ ใส่กระเทียม ขิง และพริกแกงหรือโคชูจัง", "เติมน้ำหรือน้ำซุปและซีอิ๊ว", "ใส่เต้าหู้หั่นเต๋า เคี่ยวเบา ๆ 5 นาที", "ข้นด้วยแป้งข้าวโพดละลายน้ำ โรยต้นหอม"]),
  r("tomato_egg", "both", "chinese", "main", 10, "Tomato and egg stir-fry", "มะเขือเทศผัดไข่",
    "tomato; egg", "sugar spring_onion soy_sauce ketchup rice", "",
    ["Scramble the eggs softly and lift out.", "Fry chopped tomatoes until they break down.", "Add a pinch of sugar and salt (or a spoon of ketchup).", "Return the eggs, toss and serve over rice."],
    ["ผัดไข่ให้พอนุ่มแล้วตักขึ้น", "ผัดมะเขือเทศหั่นจนเริ่มเละ", "ใส่น้ำตาลและเกลือเล็กน้อย (หรือซอสมะเขือเทศหนึ่งช้อน)", "ใส่ไข่กลับลงไป คลุกแล้วราดข้าว"]),
  r("char_siu", "both", "chinese", "main", 45, "Char siu pork", "หมูแดง",
    "pork; honey|sugar; soy_sauce", "oyster_sauce garlic cinnamon rice cucumber", "",
    ["Marinate strips of pork with soy, honey, oyster sauce, garlic and a pinch of cinnamon for 30 minutes.", "Roast at 200°C for 25 minutes, basting halfway.", "Brush with more honey and roast 5 minutes until sticky.", "Rest, slice and serve with rice and cucumber."],
    ["หมักหมูหั่นเป็นแท่งกับซีอิ๊ว น้ำผึ้ง ซอสหอยนางรม กระเทียม และอบเชยเล็กน้อย 30 นาที", "อบ 200°C ราว 25 นาที ทาซอสครึ่งทาง", "ทาน้ำผึ้งเพิ่ม อบต่อ 5 นาทีจนเหนียวเงา", "พักแล้วหั่น เสิร์ฟกับข้าวและแตงกวา"]),
  r("chow_mein", "both", "chinese", "main", 15, "Chow mein", "เส้นหมี่ผัดแบบจีน (เชาเหมิน)",
    "noodles|instant_noodles; cabbage|carrot|bean_sprouts|pak_choi; soy_sauce", "chicken pork shrimp tofu oyster_sauce spring_onion garlic sesame_oil", "noodles>pasta",
    ["Boil the noodles and drain well.", "Stir-fry meat or tofu with garlic, then the vegetables.", "Add noodles, soy and oyster sauce; toss on high heat.", "Finish with sesame oil and spring onion."],
    ["ต้มเส้น สะเด็ดน้ำให้แห้ง", "ผัดเนื้อสัตว์หรือเต้าหู้กับกระเทียม ตามด้วยผัก", "ใส่เส้น ซีอิ๊ว และซอสหอยนางรม ผัดไฟแรง", "ราดน้ำมันงา โรยต้นหอม"]),
  r("beef_broccoli", "both", "chinese", "main", 20, "Beef and broccoli", "เนื้อผัดบรอกโคลี",
    "beef; broccoli; oyster_sauce|soy_sauce", "garlic ginger cornflour sugar rice", "broccoli>chinese_kale,pak_choi",
    ["Slice beef thinly and toss with soy and cornflour.", "Blanch broccoli for 1 minute.", "Sear the beef on high heat; add garlic and ginger.", "Add broccoli and oyster sauce with a splash of water; toss until glossy."],
    ["หั่นเนื้อบาง ๆ คลุกซีอิ๊วและแป้งข้าวโพด", "ลวกบรอกโคลี 1 นาที", "ผัดเนื้อไฟแรงจัด ใส่กระเทียมและขิง", "ใส่บรอกโคลี ซอสหอยนางรม และน้ำเล็กน้อย ผัดจนเงา"]),
  r("hot_sour_soup", "both", "chinese", "soup", 20, "Hot and sour soup", "ซุปเปรี้ยวเผ็ดแบบจีน",
    "tofu|mushroom|pork; egg; vinegar; soy_sauce; stock", "pepper cornflour chilli spring_onion", "",
    ["Bring stock to the boil with sliced mushrooms, tofu and pork.", "Season with soy sauce, vinegar and lots of white pepper.", "Thicken with cornflour water.", "Stir in beaten egg in a thin stream; finish with spring onion."],
    ["ต้มน้ำซุปกับเห็ด เต้าหู้ และหมูหั่นเส้น", "ปรุงด้วยซีอิ๊ว น้ำส้มสายชู และพริกไทยขาวเยอะ ๆ", "ข้นด้วยแป้งข้าวโพดละลายน้ำ", "ค่อย ๆ รินไข่ตีเป็นสาย โรยต้นหอม"]),
  r("steamed_fish_ginger", "both", "chinese", "main", 20, "Steamed fish with ginger and soy", "ปลานึ่งซีอิ๊ว",
    "fish; ginger; soy_sauce", "spring_onion sesame_oil oil coriander", "",
    ["Lay the fish on a plate with sliced ginger; steam 8–12 minutes.", "Pour off the liquid and top with shredded ginger and spring onion.", "Heat a spoon of oil until smoking and pour over to sizzle.", "Pour soy sauce around and add coriander."],
    ["วางปลาบนจานกับขิงซอย นึ่ง 8–12 นาที", "เทน้ำที่ออกมาทิ้ง โรยขิงซอยและต้นหอม", "เจียวน้ำมันหนึ่งช้อนให้ร้อนจัด ราดให้เสียงฉ่า", "ราดซีอิ๊วรอบ ๆ โรยผักชี"]),
  r("garlic_pak_choi", "both", "chinese", "side", 8, "Garlic pak choi", "กวางตุ้งผัดกระเทียม",
    "pak_choi|chinese_kale|spinach; garlic|garlic_powder; oyster_sauce|soy_sauce", "sesame_oil", "",
    ["Halve pak choi lengthways and rinse.", "Fry plenty of garlic in oil.", "Add the greens and a splash of water; cover 1 minute.", "Drizzle with oyster sauce and sesame oil."],
    ["ผ่ากวางตุ้งครึ่งตามยาว ล้างให้สะอาด", "เจียวกระเทียมเยอะ ๆ", "ใส่ผักกับน้ำเล็กน้อย ปิดฝา 1 นาที", "ราดซอสหอยนางรมและน้ำมันงา"]),
  r("egg_drop_soup", "both", "chinese", "soup", 10, "Egg drop soup", "ซุปไข่แบบจีน",
    "egg; stock|soy_sauce; cornflour", "spring_onion sweetcorn pepper sesame_oil tofu", "",
    ["Bring stock to a simmer (add sweetcorn or tofu if you like).", "Thicken slightly with cornflour water.", "Stir the soup in a circle and pour in beaten egg slowly to make ribbons.", "Finish with spring onion, pepper and sesame oil."],
    ["ต้มน้ำซุปพอเดือด (ใส่ข้าวโพดหรือเต้าหู้ถ้าชอบ)", "ข้นเล็กน้อยด้วยแป้งข้าวโพดละลายน้ำ", "คนน้ำซุปเป็นวงแล้วค่อย ๆ รินไข่ตีให้เป็นริ้ว", "โรยต้นหอม พริกไทย และน้ำมันงา"]),

  // ---- Japanese ----
  r("teriyaki_chicken", "both", "japanese", "main", 20, "Teriyaki chicken", "ไก่เทอริยากิ",
    "chicken; soy_sauce; sugar|honey", "ginger garlic rice spring_onion sesame_oil", "",
    ["Pan-fry chicken thighs skin side down until crisp; turn and cook through.", "Mix soy sauce, honey or sugar and a little water (and ginger).", "Pour into the pan and bubble until sticky, turning the chicken to glaze.", "Slice and serve over rice."],
    ["ทอดสะโพกไก่ด้านหนังลงจนกรอบ กลับด้านทอดจนสุก", "ผสมซีอิ๊ว น้ำผึ้งหรือน้ำตาล และน้ำเล็กน้อย (ใส่ขิงด้วยก็ได้)", "เทลงกระทะ เคี่ยวจนข้นเหนียว พลิกไก่ให้เคลือบ", "หั่นแล้ววางบนข้าว"]),
  r("oyakodon", "both", "japanese", "main", 20, "Chicken and egg rice bowl", "โอยาโกะด้ง (ข้าวหน้าไก่ไข่)",
    "chicken; egg; onion; soy_sauce; rice", "sugar stock spring_onion", "",
    ["Simmer sliced onion in stock (or water) with soy sauce and a little sugar.", "Add bite-sized chicken and cook 5 minutes.", "Pour over lightly beaten eggs, cover and cook 1 minute until just set.", "Slide over bowls of rice; top with spring onion."],
    ["ต้มหอมใหญ่ซอยในน้ำซุป (หรือน้ำ) กับซีอิ๊วและน้ำตาลเล็กน้อย", "ใส่ไก่หั่นชิ้นพอคำ ต้ม 5 นาที", "ราดไข่ตีเบา ๆ ปิดฝา 1 นาทีจนไข่เริ่มเซ็ต", "ไถลงบนข้าวสวย โรยต้นหอม"]),
  r("miso_soup", "both", "japanese", "soup", 10, "Miso soup", "ซุปมิโซะ",
    "miso; tofu|mushroom|spinach|pak_choi|spring_onion", "spring_onion stock", "",
    ["Heat stock or water until steaming.", "Add cubed tofu, mushrooms or greens; simmer 2 minutes.", "Take off the heat and whisk in miso (never boil it).", "Top with spring onion."],
    ["อุ่นน้ำซุปหรือน้ำให้มีไอ", "ใส่เต้าหู้หั่นเต๋า เห็ด หรือผัก ต้ม 2 นาที", "ปิดไฟ ละลายมิโซะลงไป (อย่าต้มให้เดือด)", "โรยต้นหอม"]),
  r("tamagoyaki", "both", "japanese", "breakfast", 15, "Japanese rolled omelette", "ทามาโกะยากิ (ไข่ม้วนญี่ปุ่น)",
    "egg; soy_sauce|salt", "sugar spring_onion stock", "",
    ["Beat eggs with a little soy sauce, sugar and a splash of stock.", "Pour a thin layer into an oiled pan; roll it up when almost set.", "Push the roll to one end, pour in more egg and roll again; repeat.", "Rest a minute and slice."],
    ["ตีไข่กับซีอิ๊ว น้ำตาล และน้ำซุปเล็กน้อย", "เทไข่บาง ๆ ลงกระทะทาน้ำมัน พอเกือบสุกให้ม้วน", "ดันม้วนไว้ปลายกระทะ เทไข่เพิ่มแล้วม้วนต่อ ทำซ้ำ", "พักสักครู่แล้วหั่น"]),
  r("katsu", "both", "japanese", "main", 30, "Pork or chicken katsu", "หมูชุบเกล็ดขนมปังทอด (คัตสึ)",
    "pork|chicken; breadcrumbs|flour; egg; oil", "curry_powder rice cabbage ketchup soy_sauce", "",
    ["Flatten the meat slightly; season.", "Dust in flour, dip in egg and press into breadcrumbs.", "Shallow-fry until deep golden and cooked through; rest 2 minutes.", "Slice and serve with shredded cabbage and rice (or a quick curry sauce)."],
    ["ทุบเนื้อให้แบนเล็กน้อย ปรุงเกลือพริกไทย", "คลุกแป้ง จุ่มไข่ แล้วกดเกล็ดขนมปังให้ทั่ว", "ทอดน้ำมันพอท่วมครึ่งชิ้นจนเหลืองเข้มและสุก พัก 2 นาที", "หั่นเป็นชิ้น เสิร์ฟกับกะหล่ำปลีซอยและข้าว (หรือราดแกงกะหรี่)"]),
  r("ramen_bowl", "both", "japanese", "main", 15, "Upgraded ramen bowl", "ราเมงชามพิเศษ",
    "instant_noodles|noodles; egg; stock|miso|soy_sauce", "spring_onion pork chicken pak_choi sweetcorn sesame_oil spinach mushroom", "",
    ["Boil an egg for 6½ minutes, cool and peel.", "Make the broth with stock (or the sachet) and a spoon of miso or soy.", "Cook the noodles and greens in the broth.", "Top with sliced meat, the halved egg, sweetcorn and spring onion."],
    ["ต้มไข่ 6 นาทีครึ่ง แช่น้ำเย็น ปอกเปลือก", "ทำน้ำซุปด้วยน้ำซุป (หรือผงในซอง) กับมิโซะหรือซีอิ๊วหนึ่งช้อน", "ต้มเส้นและผักในน้ำซุป", "วางเนื้อหั่น ไข่ผ่าครึ่ง ข้าวโพด และต้นหอม"]),
  r("yakisoba", "both", "japanese", "main", 15, "Yakisoba", "ยากิโซบะ",
    "noodles|instant_noodles; cabbage; ketchup|oyster_sauce|soy_sauce", "pork chicken bacon carrot onion spring_onion", "",
    ["Cook the noodles and drain.", "Fry the meat, then cabbage, carrot and onion.", "Add the noodles with a sauce of ketchup, soy and oyster sauce.", "Toss until coated and slightly charred."],
    ["ต้มเส้น สะเด็ดน้ำ", "ผัดเนื้อสัตว์ ตามด้วยกะหล่ำปลี แครอท และหอมใหญ่", "ใส่เส้นกับซอสที่ผสมซอสมะเขือเทศ ซีอิ๊ว และซอสหอยนางรม", "ผัดจนเคลือบทั่วและหอมไหม้นิด ๆ"]),
  r("salmon_rice_bowl", "both", "japanese", "main", 20, "Salmon rice bowl", "ข้าวหน้าแซลมอน",
    "fish; rice; soy_sauce", "avocado cucumber mayonnaise spring_onion sesame_oil honey", "fish>tuna",
    ["Glaze the salmon with soy and a little honey; pan-fry or bake until just cooked.", "Flake over warm rice.", "Add sliced avocado and cucumber.", "Drizzle with mayonnaise and a few drops of sesame oil."],
    ["ทาแซลมอนด้วยซีอิ๊วและน้ำผึ้งเล็กน้อย ทอดหรืออบพอสุก", "แกะเนื้อวางบนข้าวอุ่น", "ใส่อะโวคาโดและแตงกวาหั่น", "ราดมายองเนสและน้ำมันงาเล็กน้อย"]),
  r("onigiri", "both", "japanese", "snack", 20, "Tuna mayo rice balls", "ข้าวปั้นทูน่ามายองเนส (โอนิกิริ)",
    "rice; tuna; mayonnaise", "soy_sauce spring_onion", "tuna>fish",
    ["Mix tuna with mayonnaise and a drop of soy sauce.", "Wet and salt your hands; take a handful of warm rice.", "Make a dip, add a spoon of filling and close the rice around it.", "Press into a triangle."],
    ["ผสมทูน่ากับมายองเนสและซีอิ๊วเล็กน้อย", "ชุบมือให้เปียกแล้วแตะเกลือ ตักข้าวอุ่นหนึ่งกำมือ", "กดตรงกลางเป็นหลุม ใส่ไส้หนึ่งช้อน แล้วปิดข้าวรอบ ๆ", "กดให้เป็นรูปสามเหลี่ยม"]),

  // ---- Korean ----
  r("kimchi_fried_rice", "both", "korean", "main", 15, "Kimchi fried rice", "ข้าวผัดกิมจิ",
    "rice; kimchi; egg", "gochujang spring_onion sesame_oil pork bacon butter", "",
    ["Fry chopped kimchi (and pork or bacon) in butter or oil for 3 minutes.", "Add cold cooked rice with a splash of kimchi juice and a little gochujang.", "Toss until hot and slightly crisp.", "Top with a fried egg, spring onion and sesame oil."],
    ["ผัดกิมจิหั่น (และหมูหรือเบคอน) กับเนยหรือน้ำมัน 3 นาที", "ใส่ข้าวสวยเย็นกับน้ำกิมจิเล็กน้อยและโคชูจังนิดหน่อย", "ผัดจนร้อนทั่วและกรอบนิด ๆ", "วางไข่ดาว โรยต้นหอม ราดน้ำมันงา"]),
  r("bibimbap", "both", "korean", "main", 30, "Bibimbap", "บิบิมบับ (ข้าวยำเกาหลี)",
    "rice; egg; spinach|carrot|bean_sprouts|courgette|mushroom; gochujang|soy_sauce", "beef sesame_oil garlic kimchi cucumber", "",
    ["Cook each vegetable separately with a little sesame oil and garlic.", "Fry some mince with soy sauce if using.", "Arrange everything over rice with a fried egg in the middle.", "Add gochujang, then mix it all together to eat."],
    ["ผัดผักแต่ละอย่างแยกกันกับน้ำมันงาและกระเทียมเล็กน้อย", "ผัดเนื้อสับกับซีอิ๊วถ้ามี", "จัดทุกอย่างบนข้าว วางไข่ดาวตรงกลาง", "ใส่โคชูจัง แล้วคลุกให้เข้ากันก่อนกิน"]),
  r("bulgogi", "both", "korean", "main", 25, "Bulgogi", "บุลโกกิ (เนื้อหมักย่างเกาหลี)",
    "beef|pork; soy_sauce; sugar|honey|apple; garlic|garlic_powder", "sesame_oil onion spring_onion rice lettuce", "",
    ["Grate a little apple or pear into soy sauce with sugar, garlic and sesame oil.", "Marinate thinly sliced meat for 20 minutes.", "Cook on a very hot pan with sliced onion until caramelised.", "Serve with rice and lettuce leaves for wrapping."],
    ["ขูดแอปเปิลหรือสาลี่ลงในซีอิ๊ว ผสมน้ำตาล กระเทียม และน้ำมันงา", "หมักเนื้อหั่นบาง 20 นาที", "ผัดในกระทะร้อนจัดกับหอมใหญ่ซอยจนเป็นคาราเมล", "เสิร์ฟกับข้าวและผักกาดสำหรับห่อ"]),
  r("kimchi_jjigae", "both", "korean", "soup", 25, "Kimchi stew", "คิมจิจิเก (ซุปกิมจิ)",
    "kimchi; tofu|pork|tuna; stock|soy_sauce", "gochujang onion spring_onion sesame_oil", "",
    ["Fry kimchi and pork in sesame oil for 3 minutes.", "Add stock or water, a little kimchi juice and gochujang.", "Simmer 15 minutes, add tofu and simmer 5 more.", "Top with spring onion; serve with rice."],
    ["ผัดกิมจิกับหมูในน้ำมันงา 3 นาที", "เติมน้ำซุปหรือน้ำ น้ำกิมจิเล็กน้อย และโคชูจัง", "ต้ม 15 นาที ใส่เต้าหู้ ต้มต่ออีก 5 นาที", "โรยต้นหอม เสิร์ฟกับข้าว"]),
  r("japchae", "both", "korean", "main", 25, "Japchae", "จับเช (วุ้นเส้นผัดเกาหลี)",
    "glass_noodles; spinach|carrot|mushroom|onion; soy_sauce; sugar|honey", "sesame_oil beef egg garlic", "",
    ["Boil the glass noodles 5 minutes; drain and snip shorter.", "Stir-fry the vegetables (and beef) separately with garlic.", "Toss everything with soy sauce, sugar and sesame oil.", "Serve warm or at room temperature."],
    ["ต้มวุ้นเส้น 5 นาที สะเด็ดน้ำ ตัดให้สั้นลง", "ผัดผัก (และเนื้อ) แยกกันกับกระเทียม", "คลุกทุกอย่างกับซีอิ๊ว น้ำตาล และน้ำมันงา", "เสิร์ฟอุ่นหรือพักให้เย็น"]),
  r("korean_fried_chicken", "both", "korean", "main", 35, "Korean fried chicken", "ไก่ทอดเกาหลี",
    "chicken; flour|cornflour; gochujang|ketchup; honey|sugar", "garlic soy_sauce sesame_oil peanuts", "",
    ["Coat chicken pieces in cornflour.", "Fry until cooked, rest 5 minutes, then fry again for extra crunch.", "Simmer gochujang, ketchup, honey, garlic and soy into a glaze.", "Toss the chicken in the glaze; top with peanuts or sesame."],
    ["คลุกไก่กับแป้งข้าวโพด", "ทอดจนสุก พัก 5 นาที แล้วทอดซ้ำให้กรอบ", "เคี่ยวโคชูจัง ซอสมะเขือเทศ น้ำผึ้ง กระเทียม และซีอิ๊วเป็นซอส", "คลุกไก่ในซอส โรยถั่วหรืองา"]),
  r("pajeon", "both", "korean", "snack", 20, "Spring onion pancake", "พาจอน (แพนเค้กต้นหอม)",
    "flour; spring_onion; oil", "egg shrimp squid soy_sauce vinegar chilli", "",
    ["Mix flour with cold water (and an egg) into a thin batter.", "Lay long spring onions (and seafood) in an oiled pan and pour over the batter.", "Fry until crisp, flip and press down.", "Serve with a dip of soy sauce and vinegar."],
    ["ผสมแป้งกับน้ำเย็น (และไข่) เป็นแป้งเหลว", "วางต้นหอมยาว ๆ (และอาหารทะเล) ในกระทะทาน้ำมัน ราดแป้ง", "ทอดจนกรอบ กลับด้านแล้วกดให้แบน", "เสิร์ฟกับน้ำจิ้มซีอิ๊วผสมน้ำส้มสายชู"]),

  // ---- Southeast Asian ----
  r("pho", "both", "southeast_asian", "soup", 35, "Pho-style noodle soup", "เฝอ",
    "noodles; beef|chicken; stock; ginger|onion", "bean_sprouts thai_basil lime coriander cinnamon fish_sauce chilli spring_onion", "",
    ["Char halved onion and ginger in a dry pan.", "Simmer them in stock with cinnamon and fish sauce for 20 minutes.", "Put noodles and thinly sliced raw beef (or cooked chicken) in bowls.", "Pour over the boiling broth; add herbs, bean sprouts and lime."],
    ["ย่างหอมใหญ่ผ่าครึ่งและขิงในกระทะแห้งให้เกรียม", "ต้มในน้ำซุปกับอบเชยและน้ำปลา 20 นาที", "ใส่เส้นและเนื้อดิบหั่นบาง (หรือไก่สุก) ในชาม", "ราดน้ำซุปเดือด ๆ ใส่โหระพา ถั่วงอก และมะนาว"]),
  r("banh_mi", "both", "southeast_asian", "snack", 20, "Banh mi", "บั๋นหมี่ (แซนด์วิชเวียดนาม)",
    "bread; pork|chicken|ham|tofu; carrot|cucumber", "mayonnaise coriander chilli vinegar sugar soy_sauce", "",
    ["Quick-pickle shredded carrot in vinegar, sugar and salt for 15 minutes.", "Fry the meat or tofu with a little soy sauce.", "Split a crusty roll and spread with mayonnaise.", "Fill with meat, pickles, cucumber, coriander and chilli."],
    ["ดองแครอทซอยในน้ำส้มสายชู น้ำตาล และเกลือ 15 นาที", "ผัดเนื้อสัตว์หรือเต้าหู้กับซีอิ๊วเล็กน้อย", "ผ่าขนมปังกรอบ ทามายองเนส", "ใส่เนื้อ ผักดอง แตงกวา ผักชี และพริก"]),
  r("bun_cha", "both", "southeast_asian", "main", 30, "Vietnamese pork noodle bowl", "บุ๋นจ่า (หมูย่างกับเส้นหมี่)",
    "glass_noodles|noodles; pork_mince|pork; lettuce|cucumber|mint; fish_sauce; lime", "sugar garlic chilli carrot coriander", "",
    ["Season the mince with fish sauce, garlic and sugar; shape into small patties and grill.", "Make a dipping broth of fish sauce, lime, sugar, garlic and warm water.", "Cook the noodles and rinse in cold water.", "Serve noodles, herbs and salad with the pork in the broth."],
    ["ปรุงหมูสับกับน้ำปลา กระเทียม และน้ำตาล ปั้นเป็นแผ่นเล็กแล้วย่าง", "ทำน้ำจิ้มจากน้ำปลา มะนาว น้ำตาล กระเทียม และน้ำอุ่น", "ลวกเส้น ล้างน้ำเย็น", "เสิร์ฟเส้น ผักสมุนไพร และสลัด กับหมูในน้ำจิ้ม"]),
  r("nasi_goreng", "both", "southeast_asian", "main", 15, "Nasi goreng", "นาซิโกเร็ง (ข้าวผัดอินโดนีเซีย)",
    "rice; egg; soy_sauce; shrimp_paste|chilli", "sugar honey chicken shrimp shallot cucumber tomato", "",
    ["Fry shallot, garlic, chilli and a little shrimp paste.", "Add chicken or prawns, then cold rice.", "Season with soy sauce sweetened with sugar or honey.", "Top with a fried egg; serve with cucumber and tomato."],
    ["ผัดหอมแดง กระเทียม พริก และกะปิเล็กน้อย", "ใส่ไก่หรือกุ้ง ตามด้วยข้าวสวยเย็น", "ปรุงด้วยซีอิ๊วผสมน้ำตาลหรือน้ำผึ้งให้หวาน", "วางไข่ดาว เสิร์ฟกับแตงกวาและมะเขือเทศ"]),
  r("mee_goreng", "both", "southeast_asian", "main", 15, "Mee goreng", "หมี่โกเร็ง",
    "noodles|instant_noodles; egg; soy_sauce", "ketchup chilli tomato cabbage chicken shrimp tofu bean_sprouts lime", "",
    ["Cook the noodles and drain.", "Fry garlic, chilli and the meat or tofu; push aside and scramble the egg.", "Add cabbage, tomato and noodles with soy sauce and a spoon of ketchup.", "Toss with bean sprouts; serve with lime."],
    ["ต้มเส้น สะเด็ดน้ำ", "ผัดกระเทียม พริก และเนื้อสัตว์หรือเต้าหู้ ดันไว้ข้าง ตอกไข่ยี", "ใส่กะหล่ำ มะเขือเทศ และเส้น กับซีอิ๊วและซอสมะเขือเทศหนึ่งช้อน", "ใส่ถั่วงอก เสิร์ฟกับมะนาว"]),
  r("chicken_adobo", "both", "southeast_asian", "main", 45, "Chicken adobo", "อโดโบไก่ (ไก่ตุ๋นซีอิ๊วน้ำส้มแบบฟิลิปปินส์)",
    "chicken; soy_sauce; vinegar; garlic", "pepper sugar rice onion", "vinegar>lime",
    ["Put chicken, soy sauce, vinegar, lots of crushed garlic and pepper in a pan.", "Simmer covered for 25 minutes.", "Uncover and reduce the sauce until glossy.", "Serve with rice."],
    ["ใส่ไก่ ซีอิ๊ว น้ำส้มสายชู กระเทียมบุบเยอะ ๆ และพริกไทยลงหม้อ", "ปิดฝาเคี่ยว 25 นาที", "เปิดฝาเคี่ยวต่อจนน้ำซอสงวดเงา", "เสิร์ฟกับข้าว"]),
  r("laksa", "both", "southeast_asian", "soup", 30, "Curry laksa", "ลักซา",
    "noodles; coconut_milk; red_curry_paste|curry_powder; shrimp|chicken|tofu", "bean_sprouts lime fish_sauce egg coriander sugar", "",
    ["Fry the curry paste in a little oil until fragrant.", "Add stock or water and coconut milk; simmer 10 minutes.", "Add prawns, chicken or tofu and cook through; season with fish sauce and sugar.", "Pour over noodles; top with bean sprouts, egg and lime."],
    ["ผัดพริกแกงกับน้ำมันเล็กน้อยจนหอม", "เติมน้ำซุปหรือน้ำและกะทิ ต้ม 10 นาที", "ใส่กุ้ง ไก่ หรือเต้าหู้ต้มจนสุก ปรุงด้วยน้ำปลาและน้ำตาล", "ราดบนเส้น โรยถั่วงอก ไข่ต้ม และมะนาว"]),
  r("rendang", "both", "southeast_asian", "main", 120, "Beef rendang", "เรนดังเนื้อ",
    "beef|chicken; coconut_milk; curry_powder|red_curry_paste", "lemongrass ginger kaffir garlic shallot palm_sugar tamarind", "",
    ["Fry blended shallot, garlic, ginger and lemongrass with the curry paste.", "Add the beef and coconut milk.", "Simmer uncovered, stirring now and then, for 1½–2 hours until the sauce has cooked right down.", "Keep frying until dark and nearly dry; season with palm sugar and tamarind."],
    ["ผัดหอมแดง กระเทียม ขิง และตะไคร้ที่ปั่นแล้วกับเครื่องแกง", "ใส่เนื้อและกะทิ", "เคี่ยวโดยไม่ปิดฝา คนเป็นระยะ 1 ชั่วโมงครึ่งถึง 2 ชั่วโมงจนน้ำงวด", "ผัดต่อจนสีเข้มและเกือบแห้ง ปรุงด้วยน้ำตาลปี๊บและมะขามเปียก"]),
  r("gado_gado", "both", "southeast_asian", "salad", 25, "Gado-gado", "กาโดกาโด (สลัดผักราดซอสถั่ว)",
    "potato|green_beans|cabbage|bean_sprouts; egg; peanut_butter|peanuts", "tofu cucumber lime soy_sauce chilli sweet_chilli_sauce", "",
    ["Boil potatoes and eggs; blanch beans, cabbage and bean sprouts.", "Fry cubes of tofu until golden.", "Make a sauce of peanut butter, soy, lime, chilli and warm water.", "Arrange everything and pour over the sauce."],
    ["ต้มมันฝรั่งและไข่ ลวกถั่วฝักยาว กะหล่ำ และถั่วงอก", "ทอดเต้าหู้หั่นเต๋าจนเหลือง", "ทำซอสจากเนยถั่ว ซีอิ๊ว มะนาว พริก และน้ำอุ่น", "จัดทุกอย่างแล้วราดซอส"]),

  // ---- Mexican ----
  r("tacos", "both", "mexican", "main", 20, "Beef tacos", "ทาโก้เนื้อ",
    "tortillas; beef|chicken|pork_mince; cumin|paprika", "lettuce tomato cheese avocado onion lime chilli yogurt", "",
    ["Brown the mince with onion, cumin, paprika and a pinch of chilli.", "Warm the tortillas in a dry pan.", "Fill with meat, lettuce, tomato and cheese.", "Add avocado, lime and a spoon of yogurt."],
    ["ผัดเนื้อสับกับหอมใหญ่ ยี่หร่า ปาปริก้า และพริกเล็กน้อย", "อุ่นแผ่นแป้งในกระทะแห้ง", "ใส่เนื้อ ผักกาด มะเขือเทศ และชีส", "เพิ่มอะโวคาโด มะนาว และโยเกิร์ตหนึ่งช้อน"]),
  r("quesadilla", "both", "mexican", "snack", 10, "Cheese quesadilla", "เกซาดิย่าชีส",
    "tortillas; cheese", "chicken kidney_beans sweetcorn bell_pepper spring_onion chilli", "",
    ["Scatter cheese and fillings over half a tortilla.", "Fold over.", "Dry-fry 2 minutes a side until crisp and the cheese melts.", "Cut into wedges."],
    ["โรยชีสและไส้บนแผ่นแป้งครึ่งหนึ่ง", "พับครึ่ง", "ทอดในกระทะแห้งด้านละ 2 นาทีจนกรอบและชีสละลาย", "ตัดเป็นชิ้นสามเหลี่ยม"]),
  r("burrito_bowl", "both", "mexican", "main", 25, "Burrito bowl", "เบอร์ริโตโบวล์",
    "rice; kidney_beans; sweetcorn|tomato|avocado; lime", "chicken beef cumin paprika cheese lettuce coriander", "",
    ["Cook rice and stir in lime juice and coriander.", "Warm the beans with cumin and paprika.", "Cook spiced chicken or beef if you have it.", "Build bowls with rice, beans, corn, tomato, avocado and cheese."],
    ["หุงข้าว คลุกน้ำมะนาวและผักชี", "อุ่นถั่วกับยี่หร่าและปาปริก้า", "ผัดไก่หรือเนื้อปรุงเครื่องเทศถ้ามี", "จัดชามด้วยข้าว ถั่ว ข้าวโพด มะเขือเทศ อะโวคาโด และชีส"]),
  r("chilli_con_carne", "both", "mexican", "main", 50, "Chilli con carne", "ชิลลีคอนคาร์เน",
    "beef|pork_mince; kidney_beans; tinned_tomato|tomato; onion", "cumin paprika chilli garlic bell_pepper rice cheese", "",
    ["Soften onion, garlic and peppers.", "Brown the mince with cumin, paprika and chilli.", "Add tomatoes and beans; simmer 30 minutes.", "Serve with rice, cheese and a dollop of yogurt."],
    ["ผัดหอมใหญ่ กระเทียม และพริกหวานจนนิ่ม", "ใส่เนื้อสับผัดกับยี่หร่า ปาปริก้า และพริก", "ใส่มะเขือเทศและถั่ว เคี่ยว 30 นาที", "เสิร์ฟกับข้าว ชีส และโยเกิร์ตหนึ่งช้อน"]),
  r("guacamole", "both", "mexican", "snack", 10, "Guacamole", "กัวคาโมเล",
    "avocado; lime; onion|tomato", "coriander chilli tortillas garlic", "",
    ["Mash ripe avocados roughly.", "Mix in lime juice and salt straight away.", "Add finely chopped onion, tomato, chilli and coriander.", "Serve with toasted tortilla wedges."],
    ["บดอะโวคาโดสุกหยาบ ๆ", "ใส่น้ำมะนาวและเกลือทันที", "ใส่หอมใหญ่ มะเขือเทศ พริก และผักชีสับละเอียด", "เสิร์ฟกับแผ่นแป้งตอร์ติญ่าอบกรอบ"]),
  r("huevos_rancheros", "both", "mexican", "breakfast", 20, "Huevos rancheros", "อูเอโวสรันเชโรส (ไข่ดาวซอสมะเขือเทศบนแป้ง)",
    "egg; tortillas; tinned_tomato|tomato", "kidney_beans chilli onion avocado cheese coriander", "",
    ["Simmer tomatoes with onion and chilli into a quick salsa.", "Warm tortillas and refried or plain beans.", "Fry the eggs.", "Layer tortilla, beans, egg and salsa; top with avocado and cheese."],
    ["เคี่ยวมะเขือเทศกับหอมใหญ่และพริกเป็นซัลซ่าแบบเร็ว", "อุ่นแผ่นแป้งและถั่ว", "ทอดไข่ดาว", "วางซ้อนแผ่นแป้ง ถั่ว ไข่ และซัลซ่า โรยอะโวคาโดและชีส"]),
  r("fajitas", "both", "mexican", "main", 25, "Chicken fajitas", "ฟาฮีตาไก่",
    "chicken|beef; bell_pepper; onion; tortillas", "paprika cumin lime cheese yogurt avocado", "",
    ["Slice chicken, peppers and onion into strips.", "Toss with paprika, cumin, oil and lime.", "Cook on a very hot pan until charred at the edges.", "Serve in warm tortillas with yogurt and cheese."],
    ["หั่นไก่ พริกหวาน และหอมใหญ่เป็นเส้น", "คลุกปาปริก้า ยี่หร่า น้ำมัน และมะนาว", "ผัดในกระทะร้อนจัดจนขอบเกรียม", "เสิร์ฟในแผ่นแป้งอุ่นกับโยเกิร์ตและชีส"]),

  // ---- American ----
  r("mac_and_cheese", "both", "american", "main", 30, "Mac and cheese", "แมคแอนด์ชีส",
    "pasta; cheese; milk; butter", "flour breadcrumbs pepper ham", "",
    ["Boil short pasta.", "Melt butter, stir in a spoon of flour, then whisk in milk until thick.", "Stir in plenty of cheese until melted, then the pasta.", "Eat as it is, or top with breadcrumbs and grill until golden."],
    ["ต้มพาสต้าเส้นสั้น", "ละลายเนย ใส่แป้งหนึ่งช้อน แล้วตีนมลงไปจนข้น", "ใส่ชีสเยอะ ๆ จนละลาย แล้วใส่เส้น", "กินได้เลย หรือโรยเกล็ดขนมปังแล้วอบไฟบนจนเหลือง"]),
  r("burger", "both", "american", "main", 20, "Homemade burgers", "เบอร์เกอร์ทำเอง",
    "beef|pork_mince|chicken; bread; onion|lettuce|tomato", "cheese ketchup mayonnaise egg", "",
    ["Season mince with salt and pepper; shape into patties slightly wider than the buns.", "Cook in a hot pan 3–4 minutes a side (pork and chicken must be cooked through).", "Add cheese for the last minute.", "Serve in toasted buns with lettuce, tomato, onion and sauces."],
    ["ปรุงเนื้อสับด้วยเกลือและพริกไทย ปั้นเป็นแผ่นใหญ่กว่าขนมปังเล็กน้อย", "ย่างในกระทะร้อนด้านละ 3–4 นาที (หมูและไก่ต้องสุกทั่ว)", "วางชีสในนาทีสุดท้าย", "ใส่ในขนมปังปิ้งกับผักกาด มะเขือเทศ หอมใหญ่ และซอส"]),
  r("bbq_wings", "both", "american", "snack", 50, "Sticky BBQ chicken wings", "ปีกไก่บาร์บีคิว",
    "chicken; honey|sugar; ketchup|soy_sauce", "paprika garlic_powder garlic vinegar", "",
    ["Toss wings with oil, salt and paprika; roast at 220°C for 35 minutes.", "Simmer ketchup, honey, soy, garlic and a dash of vinegar into a glaze.", "Toss the wings in the glaze.", "Roast 5–10 minutes more until sticky."],
    ["คลุกปีกไก่กับน้ำมัน เกลือ และปาปริก้า อบ 220°C ราว 35 นาที", "เคี่ยวซอสมะเขือเทศ น้ำผึ้ง ซีอิ๊ว กระเทียม และน้ำส้มสายชูเล็กน้อยเป็นซอส", "คลุกปีกไก่ในซอส", "อบต่อ 5–10 นาทีจนเหนียวเงา"]),
  r("caesar_salad", "both", "american", "salad", 20, "Chicken Caesar salad", "ซีซาร์สลัดไก่",
    "lettuce; cheese; bread|breadcrumbs; mayonnaise|yogurt", "chicken garlic lime bacon egg", "",
    ["Toast cubes of bread in oil to make croutons.", "Grill or pan-fry the chicken; slice.", "Mix mayonnaise with garlic, lemon and grated cheese for the dressing.", "Toss lettuce with dressing, croutons, chicken and more cheese."],
    ["ทอดขนมปังหั่นเต๋ากับน้ำมันเป็นครูตอง", "ย่างหรือทอดไก่ แล้วหั่น", "ผสมมายองเนสกับกระเทียม มะนาว และชีสขูดเป็นน้ำสลัด", "คลุกผักกาดกับน้ำสลัด ครูตอง ไก่ และชีสเพิ่ม"]),
  r("chicken_noodle_soup", "both", "american", "soup", 35, "Chicken noodle soup", "ซุปไก่ใส่เส้น",
    "chicken; noodles|pasta; carrot|celery|onion; stock", "garlic parsley pepper", "",
    ["Soften onion, carrot and celery in a little butter.", "Add stock and the chicken; simmer 20 minutes.", "Shred the chicken and return it with the noodles; cook until tender.", "Season and finish with parsley."],
    ["ผัดหอมใหญ่ แครอท และคื่นฉ่ายกับเนยเล็กน้อยจนนิ่ม", "เติมน้ำซุปและไก่ ต้ม 20 นาที", "ฉีกไก่ใส่กลับลงไปพร้อมเส้น ต้มจนเส้นนุ่ม", "ปรุงรส โรยพาร์สลีย์"]),
];
