/**
 * Regenerates supabase/seed.sql from src/lib/catalog.ts so the database catalogue and the app never drift.
 * Run: npm run gen:seed
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { CATALOG, SHELF_LIFE } from "../src/lib/catalog";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const rows = Object.values(CATALOG).map((c) => {
  const shelf = SHELF_LIFE[c.id];
  return `  (${q(c.id)}, ${q(c.th)}, ${q(c.en)}, ${q(c.cat)}, ${q(c.u)}, ${c.pack}, ${c.use}, ${c.thb}, ${c.gbp}, array[${c.aliases.map(q).join(", ")}], ${shelf ? shelf.days : "null"}, ${shelf ? q(shelf.kind) : "null"})`;
});

const sql = `-- Generated by scripts/gen-seed.ts from src/lib/catalog.ts. Do not edit by hand.
-- Run after migrations 0001 and 0002.
insert into public.ingredients (slug, name_th, name_en, category, unit, pack_size, portion, price_thb, price_gbp, aliases, shelf_days, shelf_kind) values
${rows.join(",\n")}
on conflict (slug) do update set
  name_th = excluded.name_th, name_en = excluded.name_en, category = excluded.category, unit = excluded.unit,
  pack_size = excluded.pack_size, portion = excluded.portion, price_thb = excluded.price_thb,
  price_gbp = excluded.price_gbp, aliases = excluded.aliases, shelf_days = excluded.shelf_days, shelf_kind = excluded.shelf_kind;
`;

writeFileSync(join(__dirname, "..", "supabase", "seed.sql"), sql);
console.log(`Wrote ${rows.length} ingredients to supabase/seed.sql`);
